package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.AccountIndustryPO;
import com.inmind.mybatis.entity.AccountIndustryPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface AccountIndustryPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_industry
     *
     * @mbg.generated
     */
    long countByExample(AccountIndustryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_industry
     *
     * @mbg.generated
     */
    int deleteByExample(AccountIndustryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_industry
     *
     * @mbg.generated
     */
    @Insert({
        "insert into account_industry (account_id, industry_code, ",
        "created_at, updated_at)",
        "values (#{accountId,jdbcType=BIGINT}, #{industryCode,jdbcType=INTEGER}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(AccountIndustryPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_industry
     *
     * @mbg.generated
     */
    int insertSelective(AccountIndustryPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_industry
     *
     * @mbg.generated
     */
    List<AccountIndustryPO> selectByExampleWithRowbounds(AccountIndustryPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_industry
     *
     * @mbg.generated
     */
    List<AccountIndustryPO> selectByExample(AccountIndustryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_industry
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AccountIndustryPO record, @Param("example") AccountIndustryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_industry
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AccountIndustryPO record, @Param("example") AccountIndustryPOExample example);
}