package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.AccountLocationPO;
import com.inmind.mybatis.entity.AccountLocationPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface AccountLocationPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_location
     *
     * @mbg.generated
     */
    long countByExample(AccountLocationPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_location
     *
     * @mbg.generated
     */
    int deleteByExample(AccountLocationPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_location
     *
     * @mbg.generated
     */
    @Insert({
        "insert into account_location (account_id, location_id, ",
        "created_at, updated_at)",
        "values (#{accountId,jdbcType=BIGINT}, #{locationId,jdbcType=BIGINT}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(AccountLocationPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_location
     *
     * @mbg.generated
     */
    int insertSelective(AccountLocationPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_location
     *
     * @mbg.generated
     */
    List<AccountLocationPO> selectByExampleWithRowbounds(AccountLocationPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_location
     *
     * @mbg.generated
     */
    List<AccountLocationPO> selectByExample(AccountLocationPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_location
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AccountLocationPO record, @Param("example") AccountLocationPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_location
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AccountLocationPO record, @Param("example") AccountLocationPOExample example);
}