package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.AccountRolePO;
import com.inmind.mybatis.entity.AccountRolePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface AccountRolePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role
     *
     * @mbg.generated
     */
    long countByExample(AccountRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role
     *
     * @mbg.generated
     */
    int deleteByExample(AccountRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role
     *
     * @mbg.generated
     */
    @Insert({
        "insert into account_role (company_id, account_id, ",
        "role_id, created_by, ",
        "updated_by, created_at, ",
        "updated_at)",
        "values (#{companyId,jdbcType=BIGINT}, #{accountId,jdbcType=BIGINT}, ",
        "#{roleId,jdbcType=BIGINT}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(AccountRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role
     *
     * @mbg.generated
     */
    int insertSelective(AccountRolePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role
     *
     * @mbg.generated
     */
    List<AccountRolePO> selectByExampleWithRowbounds(AccountRolePOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role
     *
     * @mbg.generated
     */
    List<AccountRolePO> selectByExample(AccountRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AccountRolePO record, @Param("example") AccountRolePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table account_role
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AccountRolePO record, @Param("example") AccountRolePOExample example);
}