package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.ContactPO;
import com.inmind.mybatis.entity.ContactPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface ContactPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    long countByExample(ContactPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    int deleteByExample(ContactPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    @Insert({
        "insert into contact (company_id, people_id, ",
        "avatar, chinese_name, ",
        "english_name, gender, ",
        "mobile, work_tel, ",
        "work_phone, other_tel, ",
        "private_email, work_email, ",
        "other_email, wechat_no, ",
        "qq_no, weibo, contact_integrity, ",
        "org_id, org_name, industry, ",
        "position, contact_type, ",
        "recruit_location_ids, recruit_functions, ",
        "owner_id, created_by, ",
        "updated_by, created_at, ",
        "updated_at, latest_contact_at, ",
        "introduce)",
        "values (#{companyId,jdbcType=BIGINT}, #{peopleId,jdbcType=BIGINT}, ",
        "#{avatar,jdbcType=VARCHAR}, #{chineseName,jdbcType=VARCHAR}, ",
        "#{englishName,jdbcType=VARCHAR}, #{gender,jdbcType=INTEGER}, ",
        "#{mobile,jdbcType=VARCHAR}, #{workTel,jdbcType=VARCHAR}, ",
        "#{workPhone,jdbcType=VARCHAR}, #{otherTel,jdbcType=VARCHAR}, ",
        "#{privateEmail,jdbcType=VARCHAR}, #{workEmail,jdbcType=VARCHAR}, ",
        "#{otherEmail,jdbcType=VARCHAR}, #{wechatNo,jdbcType=VARCHAR}, ",
        "#{qqNo,jdbcType=VARCHAR}, #{weibo,jdbcType=VARCHAR}, #{contactIntegrity,jdbcType=DECIMAL}, ",
        "#{orgId,jdbcType=BIGINT}, #{orgName,jdbcType=VARCHAR}, #{industry,jdbcType=INTEGER}, ",
        "#{position,jdbcType=VARCHAR}, #{contactType,jdbcType=INTEGER}, ",
        "#{recruitLocationIds,jdbcType=VARCHAR}, #{recruitFunctions,jdbcType=VARCHAR}, ",
        "#{ownerId,jdbcType=BIGINT}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{latestContactAt,jdbcType=TIMESTAMP}, ",
        "#{introduce,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ContactPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    int insertSelective(ContactPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    List<ContactPO> selectByExampleWithBLOBsWithRowbounds(ContactPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    List<ContactPO> selectByExampleWithBLOBs(ContactPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    List<ContactPO> selectByExampleWithRowbounds(ContactPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    List<ContactPO> selectByExample(ContactPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ContactPO record, @Param("example") ContactPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ContactPO record, @Param("example") ContactPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ContactPO record, @Param("example") ContactPOExample example);
}