package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.DepartmentPO;
import com.inmind.mybatis.entity.DepartmentPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface DepartmentPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    long countByExample(DepartmentPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    int deleteByExample(DepartmentPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    @Insert({
        "insert into department (company_id, department_name, ",
        "department_desc, parent_department_id, ",
        "department_type, created_by, ",
        "updated_by, created_at, ",
        "updated_at)",
        "values (#{companyId,jdbcType=BIGINT}, #{departmentName,jdbcType=VARCHAR}, ",
        "#{departmentDesc,jdbcType=VARCHAR}, #{parentDepartmentId,jdbcType=BIGINT}, ",
        "#{departmentType,jdbcType=INTEGER}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(DepartmentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    int insertSelective(DepartmentPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    List<DepartmentPO> selectByExampleWithRowbounds(DepartmentPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    List<DepartmentPO> selectByExample(DepartmentPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DepartmentPO record, @Param("example") DepartmentPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DepartmentPO record, @Param("example") DepartmentPOExample example);
}