package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.DepartmentResumePO;
import com.inmind.mybatis.entity.DepartmentResumePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface DepartmentResumePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_resume
     *
     * @mbg.generated
     */
    long countByExample(DepartmentResumePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_resume
     *
     * @mbg.generated
     */
    int deleteByExample(DepartmentResumePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_resume
     *
     * @mbg.generated
     */
    @Insert({
        "insert into department_resume (company_id, resume_id, ",
        "people_id, shared_to_department, ",
        "created_by, created_at, ",
        "updated_at)",
        "values (#{companyId,jdbcType=BIGINT}, #{resumeId,jdbcType=BIGINT}, ",
        "#{peopleId,jdbcType=BIGINT}, #{sharedToDepartment,jdbcType=BIGINT}, ",
        "#{createdBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(DepartmentResumePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_resume
     *
     * @mbg.generated
     */
    int insertSelective(DepartmentResumePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_resume
     *
     * @mbg.generated
     */
    List<DepartmentResumePO> selectByExampleWithRowbounds(DepartmentResumePOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_resume
     *
     * @mbg.generated
     */
    List<DepartmentResumePO> selectByExample(DepartmentResumePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_resume
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DepartmentResumePO record, @Param("example") DepartmentResumePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_resume
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DepartmentResumePO record, @Param("example") DepartmentResumePOExample example);
}