package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.DictRelationPO;
import com.inmind.mybatis.entity.DictRelationPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface DictRelationPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_relation
     *
     * @mbg.generated
     */
    long countByExample(DictRelationPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_relation
     *
     * @mbg.generated
     */
    int deleteByExample(DictRelationPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_relation
     *
     * @mbg.generated
     */
    @Insert({
        "insert into dict_relation (dict_type, parent_code, ",
        "child_code, created_by, ",
        "updated_by, created_at, ",
        "updated_at, parent_type)",
        "values (#{dictType,jdbcType=VARCHAR}, #{parentCode,jdbcType=INTEGER}, ",
        "#{childCode,jdbcType=INTEGER}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{parentType,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(DictRelationPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_relation
     *
     * @mbg.generated
     */
    int insertSelective(DictRelationPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_relation
     *
     * @mbg.generated
     */
    List<DictRelationPO> selectByExampleWithRowbounds(DictRelationPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_relation
     *
     * @mbg.generated
     */
    List<DictRelationPO> selectByExample(DictRelationPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_relation
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") DictRelationPO record, @Param("example") DictRelationPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table dict_relation
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") DictRelationPO record, @Param("example") DictRelationPOExample example);
}