package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.ExternalJobPO;
import com.inmind.mybatis.entity.ExternalJobPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface ExternalJobPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_job
     *
     * @mbg.generated
     */
    long countByExample(ExternalJobPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_job
     *
     * @mbg.generated
     */
    int deleteByExample(ExternalJobPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_job
     *
     * @mbg.generated
     */
    @Insert({
        "insert into external_job (org_id, title, ",
        "salary_lower, salary_upper, ",
        "location_id, source, ",
        "source_url, pub_at, ",
        "created_at, updated_at)",
        "values (#{orgId,jdbcType=BIGINT}, #{title,jdbcType=VARCHAR}, ",
        "#{salaryLower,jdbcType=DECIMAL}, #{salaryUpper,jdbcType=DECIMAL}, ",
        "#{locationId,jdbcType=BIGINT}, #{source,jdbcType=VARCHAR}, ",
        "#{sourceUrl,jdbcType=VARCHAR}, #{pubAt,jdbcType=TIMESTAMP}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ExternalJobPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_job
     *
     * @mbg.generated
     */
    int insertSelective(ExternalJobPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_job
     *
     * @mbg.generated
     */
    List<ExternalJobPO> selectByExampleWithRowbounds(ExternalJobPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_job
     *
     * @mbg.generated
     */
    List<ExternalJobPO> selectByExample(ExternalJobPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_job
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ExternalJobPO record, @Param("example") ExternalJobPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table external_job
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ExternalJobPO record, @Param("example") ExternalJobPOExample example);
}