package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.FavoritePO;
import com.inmind.mybatis.entity.FavoritePOExample;
import com.inmind.mybatis.entity.FavoritePOWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface FavoritePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated
     */
    long countByExample(FavoritePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated
     */
    int deleteByExample(FavoritePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated
     */
    @Insert({
        "insert into favorite (company_id, name, ",
        "account_id, type, ",
        "ref_id, description, ",
        "parent_id, path_id, ",
        "is_leaf, is_shared, ",
        "shared_by, created_by, ",
        "updated_by, created_at, ",
        "updated_at, path_name, ",
        "marks, tags, ",
        "query)",
        "values (#{companyId,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{accountId,jdbcType=BIGINT}, #{type,jdbcType=INTEGER}, ",
        "#{refId,jdbcType=BIGINT}, #{description,jdbcType=VARCHAR}, ",
        "#{parentId,jdbcType=BIGINT}, #{pathId,jdbcType=VARCHAR}, ",
        "#{isLeaf,jdbcType=INTEGER}, #{isShared,jdbcType=INTEGER}, ",
        "#{sharedBy,jdbcType=BIGINT}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{pathName,jdbcType=VARCHAR}, ",
        "#{marks,jdbcType=VARCHAR}, #{tags,jdbcType=LONGVARCHAR}, ",
        "#{query,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(FavoritePOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated
     */
    int insertSelective(FavoritePOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated
     */
    List<FavoritePOWithBLOBs> selectByExampleWithBLOBsWithRowbounds(FavoritePOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated
     */
    List<FavoritePOWithBLOBs> selectByExampleWithBLOBs(FavoritePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated
     */
    List<FavoritePO> selectByExampleWithRowbounds(FavoritePOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated
     */
    List<FavoritePO> selectByExample(FavoritePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FavoritePOWithBLOBs record, @Param("example") FavoritePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") FavoritePOWithBLOBs record, @Param("example") FavoritePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FavoritePO record, @Param("example") FavoritePOExample example);
}