package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.FavoriteTagPO;
import com.inmind.mybatis.entity.FavoriteTagPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface FavoriteTagPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_tag
     *
     * @mbg.generated
     */
    long countByExample(FavoriteTagPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_tag
     *
     * @mbg.generated
     */
    int deleteByExample(FavoriteTagPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_tag
     *
     * @mbg.generated
     */
    @Insert({
        "insert into favorite_tag (company_id, name, ",
        "type, owner_id, created_by, ",
        "updated_by, created_at, ",
        "updated_at)",
        "values (#{companyId,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{type,jdbcType=INTEGER}, #{ownerId,jdbcType=BIGINT}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(FavoriteTagPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_tag
     *
     * @mbg.generated
     */
    int insertSelective(FavoriteTagPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_tag
     *
     * @mbg.generated
     */
    List<FavoriteTagPO> selectByExampleWithRowbounds(FavoriteTagPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_tag
     *
     * @mbg.generated
     */
    List<FavoriteTagPO> selectByExample(FavoriteTagPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_tag
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") FavoriteTagPO record, @Param("example") FavoriteTagPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table favorite_tag
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") FavoriteTagPO record, @Param("example") FavoriteTagPOExample example);
}