package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.IdSequencePO;
import com.inmind.mybatis.entity.IdSequencePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.session.RowBounds;

public interface IdSequencePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_sequence
     *
     * @mbg.generated
     */
    long countByExample(IdSequencePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_sequence
     *
     * @mbg.generated
     */
    int deleteByExample(IdSequencePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_sequence
     *
     * @mbg.generated
     */
    @Insert({
        "insert into id_sequence (value, updated_at)",
        "values (#{value,jdbcType=BIGINT}, #{updatedAt,jdbcType=TIMESTAMP})"
    })
    int insert(IdSequencePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_sequence
     *
     * @mbg.generated
     */
    int insertSelective(IdSequencePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_sequence
     *
     * @mbg.generated
     */
    List<IdSequencePO> selectByExampleWithRowbounds(IdSequencePOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_sequence
     *
     * @mbg.generated
     */
    List<IdSequencePO> selectByExample(IdSequencePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_sequence
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") IdSequencePO record, @Param("example") IdSequencePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table id_sequence
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") IdSequencePO record, @Param("example") IdSequencePOExample example);
}