package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.JobSearchStatusPO;
import com.inmind.mybatis.entity.JobSearchStatusPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface JobSearchStatusPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_search_status
     *
     * @mbg.generated
     */
    long countByExample(JobSearchStatusPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_search_status
     *
     * @mbg.generated
     */
    int deleteByExample(JobSearchStatusPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_search_status
     *
     * @mbg.generated
     */
    @Insert({
        "insert into job_search_status (resume_id, status, ",
        "created_by, updated_by, ",
        "created_at, updated_at)",
        "values (#{resumeId,jdbcType=BIGINT}, #{status,jdbcType=INTEGER}, ",
        "#{createdBy,jdbcType=BIGINT}, #{updatedBy,jdbcType=BIGINT}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(JobSearchStatusPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_search_status
     *
     * @mbg.generated
     */
    int insertSelective(JobSearchStatusPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_search_status
     *
     * @mbg.generated
     */
    List<JobSearchStatusPO> selectByExampleWithRowbounds(JobSearchStatusPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_search_status
     *
     * @mbg.generated
     */
    List<JobSearchStatusPO> selectByExample(JobSearchStatusPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_search_status
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") JobSearchStatusPO record, @Param("example") JobSearchStatusPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table job_search_status
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") JobSearchStatusPO record, @Param("example") JobSearchStatusPOExample example);
}