package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.MailReceiveLogPO;
import com.inmind.mybatis.entity.MailReceiveLogPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface MailReceiveLogPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_receive_log
     *
     * @mbg.generated
     */
    long countByExample(MailReceiveLogPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_receive_log
     *
     * @mbg.generated
     */
    int deleteByExample(MailReceiveLogPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_receive_log
     *
     * @mbg.generated
     */
    @Insert({
        "insert into mail_receive_log (last_mail_uid, created_at)",
        "values (#{lastMailUid,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(MailReceiveLogPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_receive_log
     *
     * @mbg.generated
     */
    int insertSelective(MailReceiveLogPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_receive_log
     *
     * @mbg.generated
     */
    List<MailReceiveLogPO> selectByExampleWithRowbounds(MailReceiveLogPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_receive_log
     *
     * @mbg.generated
     */
    List<MailReceiveLogPO> selectByExample(MailReceiveLogPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_receive_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MailReceiveLogPO record, @Param("example") MailReceiveLogPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_receive_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MailReceiveLogPO record, @Param("example") MailReceiveLogPOExample example);
}