package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.MailLogPO;
import com.inmind.mybatis.entity.MailLogPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface MailLogPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_log
     *
     * @mbg.generated
     */
    long countByExample(MailLogPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_log
     *
     * @mbg.generated
     */
    int deleteByExample(MailLogPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_log
     *
     * @mbg.generated
     */
    @Insert({
        "insert into mail_log (mail_id, send_account_id, ",
        "sent_at, created_at, ",
        "updated_at)",
        "values (#{mailId,jdbcType=BIGINT}, #{sendAccountId,jdbcType=BIGINT}, ",
        "#{sentAt,jdbcType=TIMESTAMP}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(MailLogPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_log
     *
     * @mbg.generated
     */
    int insertSelective(MailLogPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_log
     *
     * @mbg.generated
     */
    List<MailLogPO> selectByExampleWithRowbounds(MailLogPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_log
     *
     * @mbg.generated
     */
    List<MailLogPO> selectByExample(MailLogPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") MailLogPO record, @Param("example") MailLogPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mail_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") MailLogPO record, @Param("example") MailLogPOExample example);
}