package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.OperationConfigColumnPO;
import com.inmind.mybatis.entity.OperationConfigColumnPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface OperationConfigColumnPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_config_column
     *
     * @mbg.generated
     */
    long countByExample(OperationConfigColumnPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_config_column
     *
     * @mbg.generated
     */
    int deleteByExample(OperationConfigColumnPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_config_column
     *
     * @mbg.generated
     */
    @Insert({
        "insert into operation_config_column (config_id, column_name, ",
        "busi_name, created_by, ",
        "updated_by, created_at, ",
        "updated_at)",
        "values (#{configId,jdbcType=BIGINT}, #{columnName,jdbcType=VARCHAR}, ",
        "#{busiName,jdbcType=VARCHAR}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(OperationConfigColumnPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_config_column
     *
     * @mbg.generated
     */
    int insertSelective(OperationConfigColumnPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_config_column
     *
     * @mbg.generated
     */
    List<OperationConfigColumnPO> selectByExampleWithRowbounds(OperationConfigColumnPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_config_column
     *
     * @mbg.generated
     */
    List<OperationConfigColumnPO> selectByExample(OperationConfigColumnPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_config_column
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OperationConfigColumnPO record, @Param("example") OperationConfigColumnPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table operation_config_column
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OperationConfigColumnPO record, @Param("example") OperationConfigColumnPOExample example);
}