package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.OrganizationPO;
import com.inmind.mybatis.entity.OrganizationPOExample;
import com.inmind.mybatis.entity.OrganizationPOWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface OrganizationPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    long countByExample(OrganizationPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    int deleteByExample(OrganizationPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    @Insert({
        "insert into organization (name, simple_name, ",
        "english_name, type, ",
        "phone_no, logo_url, ",
        "site_url, financing_status, ",
        "financing_amount, legal_person, ",
        "registed_capital, registed_at, ",
        "turnover, registed_no, ",
        "registed_authority, parent_id, ",
        "nature_code, emp_scale, ",
        "emp_mean_salary, wx_public_no, ",
        "linkedin_url, weibo_url, ",
        "source, qcc_unique, ",
        "org_code, license_no, ",
        "reason_type, reason, ",
        "owner_id, created_by, ",
        "updated_by, created_at, ",
        "updated_at, latest_event_at, ",
        "latest_index_at, last_index_at, ",
        "aliases, img_urls, ",
        "financing_detail, description, ",
        "brands)",
        "values (#{name,jdbcType=VARCHAR}, #{simpleName,jdbcType=VARCHAR}, ",
        "#{englishName,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, ",
        "#{phoneNo,jdbcType=VARCHAR}, #{logoUrl,jdbcType=VARCHAR}, ",
        "#{siteUrl,jdbcType=VARCHAR}, #{financingStatus,jdbcType=INTEGER}, ",
        "#{financingAmount,jdbcType=DECIMAL}, #{legalPerson,jdbcType=VARCHAR}, ",
        "#{registedCapital,jdbcType=DECIMAL}, #{registedAt,jdbcType=TIMESTAMP}, ",
        "#{turnover,jdbcType=DECIMAL}, #{registedNo,jdbcType=VARCHAR}, ",
        "#{registedAuthority,jdbcType=VARCHAR}, #{parentId,jdbcType=BIGINT}, ",
        "#{natureCode,jdbcType=INTEGER}, #{empScale,jdbcType=INTEGER}, ",
        "#{empMeanSalary,jdbcType=INTEGER}, #{wxPublicNo,jdbcType=VARCHAR}, ",
        "#{linkedinUrl,jdbcType=VARCHAR}, #{weiboUrl,jdbcType=VARCHAR}, ",
        "#{source,jdbcType=INTEGER}, #{qccUnique,jdbcType=VARCHAR}, ",
        "#{orgCode,jdbcType=VARCHAR}, #{licenseNo,jdbcType=VARCHAR}, ",
        "#{reasonType,jdbcType=INTEGER}, #{reason,jdbcType=VARCHAR}, ",
        "#{ownerId,jdbcType=BIGINT}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{latestEventAt,jdbcType=TIMESTAMP}, ",
        "#{latestIndexAt,jdbcType=TIMESTAMP}, #{lastIndexAt,jdbcType=TIMESTAMP}, ",
        "#{aliases,jdbcType=LONGVARCHAR}, #{imgUrls,jdbcType=LONGVARCHAR}, ",
        "#{financingDetail,jdbcType=LONGVARCHAR}, #{description,jdbcType=LONGVARCHAR}, ",
        "#{brands,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(OrganizationPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    int insertSelective(OrganizationPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    List<OrganizationPOWithBLOBs> selectByExampleWithBLOBsWithRowbounds(OrganizationPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    List<OrganizationPOWithBLOBs> selectByExampleWithBLOBs(OrganizationPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    List<OrganizationPO> selectByExampleWithRowbounds(OrganizationPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    List<OrganizationPO> selectByExample(OrganizationPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrganizationPOWithBLOBs record, @Param("example") OrganizationPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") OrganizationPOWithBLOBs record, @Param("example") OrganizationPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrganizationPO record, @Param("example") OrganizationPOExample example);
}