package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.OrgHistoryPO;
import com.inmind.mybatis.entity.OrgHistoryPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface OrgHistoryPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_history
     *
     * @mbg.generated
     */
    long countByExample(OrgHistoryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_history
     *
     * @mbg.generated
     */
    int deleteByExample(OrgHistoryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_history
     *
     * @mbg.generated
     */
    @Insert({
        "insert into org_history (org_id, time_at, ",
        "title, link_url, ",
        "created_by, updated_by, ",
        "created_at, updated_at, ",
        "description)",
        "values (#{orgId,jdbcType=BIGINT}, #{timeAt,jdbcType=TIMESTAMP}, ",
        "#{title,jdbcType=VARCHAR}, #{linkUrl,jdbcType=VARCHAR}, ",
        "#{createdBy,jdbcType=BIGINT}, #{updatedBy,jdbcType=BIGINT}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{description,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(OrgHistoryPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_history
     *
     * @mbg.generated
     */
    int insertSelective(OrgHistoryPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_history
     *
     * @mbg.generated
     */
    List<OrgHistoryPO> selectByExampleWithBLOBsWithRowbounds(OrgHistoryPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_history
     *
     * @mbg.generated
     */
    List<OrgHistoryPO> selectByExampleWithBLOBs(OrgHistoryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_history
     *
     * @mbg.generated
     */
    List<OrgHistoryPO> selectByExampleWithRowbounds(OrgHistoryPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_history
     *
     * @mbg.generated
     */
    List<OrgHistoryPO> selectByExample(OrgHistoryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrgHistoryPO record, @Param("example") OrgHistoryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_history
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") OrgHistoryPO record, @Param("example") OrgHistoryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrgHistoryPO record, @Param("example") OrgHistoryPOExample example);
}