package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.OrgStockPO;
import com.inmind.mybatis.entity.OrgStockPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface OrgStockPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_stock
     *
     * @mbg.generated
     */
    long countByExample(OrgStockPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_stock
     *
     * @mbg.generated
     */
    int deleteByExample(OrgStockPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_stock
     *
     * @mbg.generated
     */
    @Insert({
        "insert into org_stock (org_id, stock_exchange, ",
        "stock_code, created_by, ",
        "updated_by, created_at, ",
        "updated_at)",
        "values (#{orgId,jdbcType=BIGINT}, #{stockExchange,jdbcType=INTEGER}, ",
        "#{stockCode,jdbcType=VARCHAR}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(OrgStockPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_stock
     *
     * @mbg.generated
     */
    int insertSelective(OrgStockPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_stock
     *
     * @mbg.generated
     */
    List<OrgStockPO> selectByExampleWithRowbounds(OrgStockPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_stock
     *
     * @mbg.generated
     */
    List<OrgStockPO> selectByExample(OrgStockPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_stock
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") OrgStockPO record, @Param("example") OrgStockPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table org_stock
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") OrgStockPO record, @Param("example") OrgStockPOExample example);
}