package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.PrivateResumePO;
import com.inmind.mybatis.entity.PrivateResumePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface PrivateResumePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_resume
     *
     * @mbg.generated
     */
    long countByExample(PrivateResumePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_resume
     *
     * @mbg.generated
     */
    int deleteByExample(PrivateResumePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_resume
     *
     * @mbg.generated
     */
    @Insert({
        "insert into private_resume (company_id, resume_id, ",
        "people_id, shared_to_account, ",
        "created_by, created_at, ",
        "updated_at)",
        "values (#{companyId,jdbcType=BIGINT}, #{resumeId,jdbcType=BIGINT}, ",
        "#{peopleId,jdbcType=BIGINT}, #{sharedToAccount,jdbcType=BIGINT}, ",
        "#{createdBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(PrivateResumePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_resume
     *
     * @mbg.generated
     */
    int insertSelective(PrivateResumePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_resume
     *
     * @mbg.generated
     */
    List<PrivateResumePO> selectByExampleWithRowbounds(PrivateResumePOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_resume
     *
     * @mbg.generated
     */
    List<PrivateResumePO> selectByExample(PrivateResumePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_resume
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PrivateResumePO record, @Param("example") PrivateResumePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table private_resume
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PrivateResumePO record, @Param("example") PrivateResumePOExample example);
}