package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.ProjectWarrantyPO;
import com.inmind.mybatis.entity.ProjectWarrantyPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface ProjectWarrantyPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_warranty
     *
     * @mbg.generated
     */
    long countByExample(ProjectWarrantyPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_warranty
     *
     * @mbg.generated
     */
    int deleteByExample(ProjectWarrantyPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_warranty
     *
     * @mbg.generated
     */
    @Insert({
        "insert into project_warranty (company_id, project_id, ",
        "resume_id, people_id, ",
        "employ_at, pass_warranty_at, ",
        "created_by, updated_by, ",
        "created_at, updated_at, ",
        "remaining_balance, status, ",
        "remark)",
        "values (#{companyId,jdbcType=BIGINT}, #{projectId,jdbcType=BIGINT}, ",
        "#{resumeId,jdbcType=BIGINT}, #{peopleId,jdbcType=BIGINT}, ",
        "#{employAt,jdbcType=TIMESTAMP}, #{passWarrantyAt,jdbcType=TIMESTAMP}, ",
        "#{createdBy,jdbcType=BIGINT}, #{updatedBy,jdbcType=BIGINT}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{remainingBalance,jdbcType=DECIMAL}, #{status,jdbcType=INTEGER}, ",
        "#{remark,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ProjectWarrantyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_warranty
     *
     * @mbg.generated
     */
    int insertSelective(ProjectWarrantyPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_warranty
     *
     * @mbg.generated
     */
    List<ProjectWarrantyPO> selectByExampleWithBLOBsWithRowbounds(ProjectWarrantyPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_warranty
     *
     * @mbg.generated
     */
    List<ProjectWarrantyPO> selectByExampleWithBLOBs(ProjectWarrantyPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_warranty
     *
     * @mbg.generated
     */
    List<ProjectWarrantyPO> selectByExampleWithRowbounds(ProjectWarrantyPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_warranty
     *
     * @mbg.generated
     */
    List<ProjectWarrantyPO> selectByExample(ProjectWarrantyPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_warranty
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProjectWarrantyPO record, @Param("example") ProjectWarrantyPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_warranty
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ProjectWarrantyPO record, @Param("example") ProjectWarrantyPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_warranty
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProjectWarrantyPO record, @Param("example") ProjectWarrantyPOExample example);
}