package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.ProjectOfferPO;
import com.inmind.mybatis.entity.ProjectOfferPOExample;
import com.inmind.mybatis.entity.ProjectOfferPOWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface ProjectOfferPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_offer
     *
     * @mbg.generated
     */
    long countByExample(ProjectOfferPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_offer
     *
     * @mbg.generated
     */
    int deleteByExample(ProjectOfferPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_offer
     *
     * @mbg.generated
     */
    @Insert({
        "insert into project_offer (company_id, project_id, ",
        "resume_id, people_id, ",
        "salary, receivables, ",
        "employ_at, sign_at, ",
        "pass_warranty_at, created_by, ",
        "updated_by, created_at, ",
        "updated_at, contactor, ",
        "contact_phone, warranty_period, ",
        "title, dept, status, ",
        "salary_detail, remark)",
        "values (#{companyId,jdbcType=BIGINT}, #{projectId,jdbcType=BIGINT}, ",
        "#{resumeId,jdbcType=BIGINT}, #{peopleId,jdbcType=BIGINT}, ",
        "#{salary,jdbcType=DECIMAL}, #{receivables,jdbcType=DECIMAL}, ",
        "#{employAt,jdbcType=TIMESTAMP}, #{signAt,jdbcType=TIMESTAMP}, ",
        "#{passWarrantyAt,jdbcType=TIMESTAMP}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{contactor,jdbcType=VARCHAR}, ",
        "#{contactPhone,jdbcType=VARCHAR}, #{warrantyPeriod,jdbcType=INTEGER}, ",
        "#{title,jdbcType=VARCHAR}, #{dept,jdbcType=VARCHAR}, #{status,jdbcType=INTEGER}, ",
        "#{salaryDetail,jdbcType=LONGVARCHAR}, #{remark,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ProjectOfferPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_offer
     *
     * @mbg.generated
     */
    int insertSelective(ProjectOfferPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_offer
     *
     * @mbg.generated
     */
    List<ProjectOfferPOWithBLOBs> selectByExampleWithBLOBsWithRowbounds(ProjectOfferPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_offer
     *
     * @mbg.generated
     */
    List<ProjectOfferPOWithBLOBs> selectByExampleWithBLOBs(ProjectOfferPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_offer
     *
     * @mbg.generated
     */
    List<ProjectOfferPO> selectByExampleWithRowbounds(ProjectOfferPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_offer
     *
     * @mbg.generated
     */
    List<ProjectOfferPO> selectByExample(ProjectOfferPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_offer
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProjectOfferPOWithBLOBs record, @Param("example") ProjectOfferPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_offer
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ProjectOfferPOWithBLOBs record, @Param("example") ProjectOfferPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_offer
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProjectOfferPO record, @Param("example") ProjectOfferPOExample example);
}