package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.ProjectTargetPO;
import com.inmind.mybatis.entity.ProjectTargetPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface ProjectTargetPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_target
     *
     * @mbg.generated
     */
    long countByExample(ProjectTargetPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_target
     *
     * @mbg.generated
     */
    int deleteByExample(ProjectTargetPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_target
     *
     * @mbg.generated
     */
    @Insert({
        "insert into project_target (company_id, project_id, ",
        "resume_id, status, ",
        "created_by, updated_by, ",
        "created_at, updated_at, ",
        "code, longlist, ",
        "recommend, interview, ",
        "offer, entry, onboard, ",
        "remark_type, remark, ",
        "people_id, is_read, ",
        "refuse_remark, is_revert, ",
        "stage_at)",
        "values (#{companyId,jdbcType=BIGINT}, #{projectId,jdbcType=BIGINT}, ",
        "#{resumeId,jdbcType=BIGINT}, #{status,jdbcType=INTEGER}, ",
        "#{createdBy,jdbcType=BIGINT}, #{updatedBy,jdbcType=BIGINT}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP}, ",
        "#{code,jdbcType=VARCHAR}, #{longlist,jdbcType=INTEGER}, ",
        "#{recommend,jdbcType=INTEGER}, #{interview,jdbcType=INTEGER}, ",
        "#{offer,jdbcType=INTEGER}, #{entry,jdbcType=INTEGER}, #{onboard,jdbcType=INTEGER}, ",
        "#{remarkType,jdbcType=INTEGER}, #{remark,jdbcType=VARCHAR}, ",
        "#{peopleId,jdbcType=BIGINT}, #{isRead,jdbcType=INTEGER}, ",
        "#{refuseRemark,jdbcType=VARCHAR}, #{isRevert,jdbcType=INTEGER}, ",
        "#{stageAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ProjectTargetPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_target
     *
     * @mbg.generated
     */
    int insertSelective(ProjectTargetPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_target
     *
     * @mbg.generated
     */
    List<ProjectTargetPO> selectByExampleWithRowbounds(ProjectTargetPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_target
     *
     * @mbg.generated
     */
    List<ProjectTargetPO> selectByExample(ProjectTargetPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_target
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProjectTargetPO record, @Param("example") ProjectTargetPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_target
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProjectTargetPO record, @Param("example") ProjectTargetPOExample example);
}