package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.QuestionGroupPO;
import com.inmind.mybatis.entity.QuestionGroupPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface QuestionGroupPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_group
     *
     * @mbg.generated
     */
    long countByExample(QuestionGroupPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_group
     *
     * @mbg.generated
     */
    int deleteByExample(QuestionGroupPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_group
     *
     * @mbg.generated
     */
    @Insert({
        "insert into question_group (company_id, title, ",
        "form_type, code, ",
        "required, created_by, ",
        "updated_by, created_at, ",
        "updated_at)",
        "values (#{companyId,jdbcType=BIGINT}, #{title,jdbcType=VARCHAR}, ",
        "#{formType,jdbcType=VARCHAR}, #{code,jdbcType=VARCHAR}, ",
        "#{required,jdbcType=INTEGER}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(QuestionGroupPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_group
     *
     * @mbg.generated
     */
    int insertSelective(QuestionGroupPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_group
     *
     * @mbg.generated
     */
    List<QuestionGroupPO> selectByExampleWithRowbounds(QuestionGroupPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_group
     *
     * @mbg.generated
     */
    List<QuestionGroupPO> selectByExample(QuestionGroupPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_group
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QuestionGroupPO record, @Param("example") QuestionGroupPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question_group
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QuestionGroupPO record, @Param("example") QuestionGroupPOExample example);
}