package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.QuestionPO;
import com.inmind.mybatis.entity.QuestionPOExample;
import com.inmind.mybatis.entity.QuestionPOWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface QuestionPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    long countByExample(QuestionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    int deleteByExample(QuestionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    @Insert({
        "insert into question (company_id, title, ",
        "form_type, type, ",
        "field, table_name, ",
        "field_type, hidden, ",
        "deleted, created_by, ",
        "updated_by, created_at, ",
        "updated_at, options, ",
        "description)",
        "values (#{companyId,jdbcType=BIGINT}, #{title,jdbcType=VARCHAR}, ",
        "#{formType,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, ",
        "#{field,jdbcType=VARCHAR}, #{tableName,jdbcType=VARCHAR}, ",
        "#{fieldType,jdbcType=VARCHAR}, #{hidden,jdbcType=INTEGER}, ",
        "#{deleted,jdbcType=INTEGER}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{options,jdbcType=LONGVARCHAR}, ",
        "#{description,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(QuestionPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    int insertSelective(QuestionPOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    List<QuestionPOWithBLOBs> selectByExampleWithBLOBsWithRowbounds(QuestionPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    List<QuestionPOWithBLOBs> selectByExampleWithBLOBs(QuestionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    List<QuestionPO> selectByExampleWithRowbounds(QuestionPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    List<QuestionPO> selectByExample(QuestionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") QuestionPOWithBLOBs record, @Param("example") QuestionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") QuestionPOWithBLOBs record, @Param("example") QuestionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table question
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") QuestionPO record, @Param("example") QuestionPOExample example);
}