package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.ResumeContributionPO;
import com.inmind.mybatis.entity.ResumeContributionPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface ResumeContributionPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_contribution
     *
     * @mbg.generated
     */
    long countByExample(ResumeContributionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_contribution
     *
     * @mbg.generated
     */
    int deleteByExample(ResumeContributionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_contribution
     *
     * @mbg.generated
     */
    @Insert({
        "insert into resume_contribution (resume_id, field_name, ",
        "contributor, created_by, ",
        "updated_by, created_at, ",
        "updated_at)",
        "values (#{resumeId,jdbcType=BIGINT}, #{fieldName,jdbcType=VARCHAR}, ",
        "#{contributor,jdbcType=BIGINT}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ResumeContributionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_contribution
     *
     * @mbg.generated
     */
    int insertSelective(ResumeContributionPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_contribution
     *
     * @mbg.generated
     */
    List<ResumeContributionPO> selectByExampleWithRowbounds(ResumeContributionPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_contribution
     *
     * @mbg.generated
     */
    List<ResumeContributionPO> selectByExample(ResumeContributionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_contribution
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ResumeContributionPO record, @Param("example") ResumeContributionPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_contribution
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ResumeContributionPO record, @Param("example") ResumeContributionPOExample example);
}