package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.ResumeHistoryPO;
import com.inmind.mybatis.entity.ResumeHistoryPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface ResumeHistoryPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_history
     *
     * @mbg.generated
     */
    long countByExample(ResumeHistoryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_history
     *
     * @mbg.generated
     */
    int deleteByExample(ResumeHistoryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_history
     *
     * @mbg.generated
     */
    @Insert({
        "insert into resume_history (resume_id, created_by, ",
        "updated_by, created_at, ",
        "updated_at, snapshot)",
        "values (#{resumeId,jdbcType=BIGINT}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{snapshot,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ResumeHistoryPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_history
     *
     * @mbg.generated
     */
    int insertSelective(ResumeHistoryPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_history
     *
     * @mbg.generated
     */
    List<ResumeHistoryPO> selectByExampleWithBLOBsWithRowbounds(ResumeHistoryPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_history
     *
     * @mbg.generated
     */
    List<ResumeHistoryPO> selectByExampleWithBLOBs(ResumeHistoryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_history
     *
     * @mbg.generated
     */
    List<ResumeHistoryPO> selectByExampleWithRowbounds(ResumeHistoryPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_history
     *
     * @mbg.generated
     */
    List<ResumeHistoryPO> selectByExample(ResumeHistoryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ResumeHistoryPO record, @Param("example") ResumeHistoryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_history
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ResumeHistoryPO record, @Param("example") ResumeHistoryPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ResumeHistoryPO record, @Param("example") ResumeHistoryPOExample example);
}