package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.ResumePO;
import com.inmind.mybatis.entity.ResumePOExample;
import com.inmind.mybatis.entity.ResumePOWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface ResumePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbg.generated
     */
    long countByExample(ResumePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbg.generated
     */
    int deleteByExample(ResumePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbg.generated
     */
    @Insert({
        "insert into resume (company_id, people_id, ",
        "copy_name, copy_reason, ",
        "avatar, chinese_name, ",
        "english_name, gender, ",
        "mobile, work_tel, ",
        "other_tel, private_email, ",
        "work_email, other_email, ",
        "birthday, marital_status, ",
        "register_location_id, address_id, ",
        "started_work_at, wechat_no, ",
        "qq_no, weibo, linkedin_url, ",
        "home_page, source, ",
        "job_search_status, expect_org_ids, ",
        "expect_location_ids, type, ",
        "owner_id, created_by, ",
        "updated_by, created_at, ",
        "updated_at, status, ",
        "work_phone, candidate_integrity, ",
        "contact_integrity, hidden, ",
        "published_at, resume_experience_id, ",
        "degree, native_location_id, ",
        "nationality_location_id, current_location_id, ",
        "address_detail, annual_salary, ",
        "candidate_no, evaluate, ",
        "dimission_period, org_name, ",
        "position, industry, ",
        "contact_type, recruit_location_ids, ",
        "recruit_functions, org_id, ",
        "introduce, expect_salary, ",
        "tech_capacity, salary_detail)",
        "values (#{companyId,jdbcType=BIGINT}, #{peopleId,jdbcType=BIGINT}, ",
        "#{copyName,jdbcType=VARCHAR}, #{copyReason,jdbcType=VARCHAR}, ",
        "#{avatar,jdbcType=VARCHAR}, #{chineseName,jdbcType=VARCHAR}, ",
        "#{englishName,jdbcType=VARCHAR}, #{gender,jdbcType=INTEGER}, ",
        "#{mobile,jdbcType=VARCHAR}, #{workTel,jdbcType=VARCHAR}, ",
        "#{otherTel,jdbcType=VARCHAR}, #{privateEmail,jdbcType=VARCHAR}, ",
        "#{workEmail,jdbcType=VARCHAR}, #{otherEmail,jdbcType=VARCHAR}, ",
        "#{birthday,jdbcType=TIMESTAMP}, #{maritalStatus,jdbcType=INTEGER}, ",
        "#{registerLocationId,jdbcType=BIGINT}, #{addressId,jdbcType=BIGINT}, ",
        "#{startedWorkAt,jdbcType=TIMESTAMP}, #{wechatNo,jdbcType=VARCHAR}, ",
        "#{qqNo,jdbcType=VARCHAR}, #{weibo,jdbcType=VARCHAR}, #{linkedinUrl,jdbcType=VARCHAR}, ",
        "#{homePage,jdbcType=VARCHAR}, #{source,jdbcType=INTEGER}, ",
        "#{jobSearchStatus,jdbcType=INTEGER}, #{expectOrgIds,jdbcType=VARCHAR}, ",
        "#{expectLocationIds,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, ",
        "#{ownerId,jdbcType=BIGINT}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{status,jdbcType=INTEGER}, ",
        "#{workPhone,jdbcType=VARCHAR}, #{candidateIntegrity,jdbcType=DECIMAL}, ",
        "#{contactIntegrity,jdbcType=DECIMAL}, #{hidden,jdbcType=INTEGER}, ",
        "#{publishedAt,jdbcType=TIMESTAMP}, #{resumeExperienceId,jdbcType=BIGINT}, ",
        "#{degree,jdbcType=INTEGER}, #{nativeLocationId,jdbcType=BIGINT}, ",
        "#{nationalityLocationId,jdbcType=BIGINT}, #{currentLocationId,jdbcType=BIGINT}, ",
        "#{addressDetail,jdbcType=VARCHAR}, #{annualSalary,jdbcType=DECIMAL}, ",
        "#{candidateNo,jdbcType=VARCHAR}, #{evaluate,jdbcType=VARCHAR}, ",
        "#{dimissionPeriod,jdbcType=VARCHAR}, #{orgName,jdbcType=VARCHAR}, ",
        "#{position,jdbcType=VARCHAR}, #{industry,jdbcType=INTEGER}, ",
        "#{contactType,jdbcType=INTEGER}, #{recruitLocationIds,jdbcType=VARCHAR}, ",
        "#{recruitFunctions,jdbcType=VARCHAR}, #{orgId,jdbcType=BIGINT}, ",
        "#{introduce,jdbcType=LONGVARCHAR}, #{expectSalary,jdbcType=LONGVARCHAR}, ",
        "#{techCapacity,jdbcType=LONGVARCHAR}, #{salaryDetail,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ResumePOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbg.generated
     */
    int insertSelective(ResumePOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbg.generated
     */
    List<ResumePOWithBLOBs> selectByExampleWithBLOBsWithRowbounds(ResumePOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbg.generated
     */
    List<ResumePOWithBLOBs> selectByExampleWithBLOBs(ResumePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbg.generated
     */
    List<ResumePO> selectByExampleWithRowbounds(ResumePOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbg.generated
     */
    List<ResumePO> selectByExample(ResumePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ResumePOWithBLOBs record, @Param("example") ResumePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ResumePOWithBLOBs record, @Param("example") ResumePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ResumePO record, @Param("example") ResumePOExample example);
}