package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.ResumeExperiencePO;
import com.inmind.mybatis.entity.ResumeExperiencePOExample;
import com.inmind.mybatis.entity.ResumeExperiencePOWithBLOBs;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface ResumeExperiencePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_experience
     *
     * @mbg.generated
     */
    long countByExample(ResumeExperiencePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_experience
     *
     * @mbg.generated
     */
    int deleteByExample(ResumeExperiencePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_experience
     *
     * @mbg.generated
     */
    @Insert({
        "insert into resume_experience (company_id, resume_id, ",
        "org_id, started_at, ",
        "ended_at, position, ",
        "functions, grade, ",
        "dept_id, annual_salary, ",
        "resume_type, contact_person_type, ",
        "contact_type, recruit_location_ids, ",
        "recruit_functions, on_job, ",
        "is_contact, created_by, ",
        "updated_by, created_at, ",
        "updated_at, superior_position, ",
        "underling_number, industry, ",
        "org_description, description, ",
        "salary_detail, performance, ",
        "left_reason)",
        "values (#{companyId,jdbcType=BIGINT}, #{resumeId,jdbcType=BIGINT}, ",
        "#{orgId,jdbcType=BIGINT}, #{startedAt,jdbcType=TIMESTAMP}, ",
        "#{endedAt,jdbcType=TIMESTAMP}, #{position,jdbcType=VARCHAR}, ",
        "#{functions,jdbcType=VARCHAR}, #{grade,jdbcType=INTEGER}, ",
        "#{deptId,jdbcType=BIGINT}, #{annualSalary,jdbcType=DECIMAL}, ",
        "#{resumeType,jdbcType=INTEGER}, #{contactPersonType,jdbcType=INTEGER}, ",
        "#{contactType,jdbcType=INTEGER}, #{recruitLocationIds,jdbcType=VARCHAR}, ",
        "#{recruitFunctions,jdbcType=VARCHAR}, #{onJob,jdbcType=INTEGER}, ",
        "#{isContact,jdbcType=INTEGER}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{superiorPosition,jdbcType=VARCHAR}, ",
        "#{underlingNumber,jdbcType=INTEGER}, #{industry,jdbcType=INTEGER}, ",
        "#{orgDescription,jdbcType=LONGVARCHAR}, #{description,jdbcType=LONGVARCHAR}, ",
        "#{salaryDetail,jdbcType=LONGVARCHAR}, #{performance,jdbcType=LONGVARCHAR}, ",
        "#{leftReason,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(ResumeExperiencePOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_experience
     *
     * @mbg.generated
     */
    int insertSelective(ResumeExperiencePOWithBLOBs record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_experience
     *
     * @mbg.generated
     */
    List<ResumeExperiencePOWithBLOBs> selectByExampleWithBLOBsWithRowbounds(ResumeExperiencePOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_experience
     *
     * @mbg.generated
     */
    List<ResumeExperiencePOWithBLOBs> selectByExampleWithBLOBs(ResumeExperiencePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_experience
     *
     * @mbg.generated
     */
    List<ResumeExperiencePO> selectByExampleWithRowbounds(ResumeExperiencePOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_experience
     *
     * @mbg.generated
     */
    List<ResumeExperiencePO> selectByExample(ResumeExperiencePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_experience
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ResumeExperiencePOWithBLOBs record, @Param("example") ResumeExperiencePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_experience
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") ResumeExperiencePOWithBLOBs record, @Param("example") ResumeExperiencePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table resume_experience
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ResumeExperiencePO record, @Param("example") ResumeExperiencePOExample example);
}