package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.SchoolPO;
import com.inmind.mybatis.entity.SchoolPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface SchoolPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated
     */
    long countByExample(SchoolPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated
     */
    int deleteByExample(SchoolPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated
     */
    @Insert({
        "insert into school (code, name, ",
        "grade, created_by, ",
        "updated_by, created_at, ",
        "updated_at, aliases)",
        "values (#{code,jdbcType=BIGINT}, #{name,jdbcType=VARCHAR}, ",
        "#{grade,jdbcType=INTEGER}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{aliases,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(SchoolPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated
     */
    int insertSelective(SchoolPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated
     */
    List<SchoolPO> selectByExampleWithBLOBsWithRowbounds(SchoolPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated
     */
    List<SchoolPO> selectByExampleWithBLOBs(SchoolPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated
     */
    List<SchoolPO> selectByExampleWithRowbounds(SchoolPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated
     */
    List<SchoolPO> selectByExample(SchoolPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SchoolPO record, @Param("example") SchoolPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") SchoolPO record, @Param("example") SchoolPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table school
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SchoolPO record, @Param("example") SchoolPOExample example);
}