package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.SpecialDatePO;
import com.inmind.mybatis.entity.SpecialDatePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface SpecialDatePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_date
     *
     * @mbg.generated
     */
    long countByExample(SpecialDatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_date
     *
     * @mbg.generated
     */
    int deleteByExample(SpecialDatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_date
     *
     * @mbg.generated
     */
    @Insert({
        "insert into special_date (date_str, type, ",
        "created_at)",
        "values (#{dateStr,jdbcType=VARCHAR}, #{type,jdbcType=INTEGER}, ",
        "#{createdAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(SpecialDatePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_date
     *
     * @mbg.generated
     */
    int insertSelective(SpecialDatePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_date
     *
     * @mbg.generated
     */
    List<SpecialDatePO> selectByExampleWithRowbounds(SpecialDatePOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_date
     *
     * @mbg.generated
     */
    List<SpecialDatePO> selectByExample(SpecialDatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_date
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SpecialDatePO record, @Param("example") SpecialDatePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table special_date
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SpecialDatePO record, @Param("example") SpecialDatePOExample example);
}