package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.TaskCodePO;
import com.inmind.mybatis.entity.TaskCodePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface TaskCodePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_code
     *
     * @mbg.generated
     */
    long countByExample(TaskCodePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_code
     *
     * @mbg.generated
     */
    int deleteByExample(TaskCodePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_code
     *
     * @mbg.generated
     */
    @Insert({
        "insert into task_code (name, code, ",
        "code_type, refer_type, ",
        "description, show_order, ",
        "result_op, main_op, ",
        "batch_op, created_by, ",
        "updated_by, created_at, ",
        "updated_at)",
        "values (#{name,jdbcType=VARCHAR}, #{code,jdbcType=VARCHAR}, ",
        "#{codeType,jdbcType=INTEGER}, #{referType,jdbcType=INTEGER}, ",
        "#{description,jdbcType=VARCHAR}, #{showOrder,jdbcType=INTEGER}, ",
        "#{resultOp,jdbcType=INTEGER}, #{mainOp,jdbcType=INTEGER}, ",
        "#{batchOp,jdbcType=INTEGER}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(TaskCodePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_code
     *
     * @mbg.generated
     */
    int insertSelective(TaskCodePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_code
     *
     * @mbg.generated
     */
    List<TaskCodePO> selectByExampleWithRowbounds(TaskCodePOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_code
     *
     * @mbg.generated
     */
    List<TaskCodePO> selectByExample(TaskCodePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_code
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskCodePO record, @Param("example") TaskCodePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_code
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskCodePO record, @Param("example") TaskCodePOExample example);
}