package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.TaskPO;
import com.inmind.mybatis.entity.TaskPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface TaskPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    long countByExample(TaskPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    int deleteByExample(TaskPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    @Insert({
        "insert into task (prev_id, task_rule_id, ",
        "prop_code, task_op_status, ",
        "task_ref_id, task_type, ",
        "description, major_id, ",
        "people_id, created_by, ",
        "updated_by, created_at, ",
        "updated_at)",
        "values (#{prevId,jdbcType=BIGINT}, #{taskRuleId,jdbcType=BIGINT}, ",
        "#{propCode,jdbcType=VARCHAR}, #{taskOpStatus,jdbcType=INTEGER}, ",
        "#{taskRefId,jdbcType=BIGINT}, #{taskType,jdbcType=INTEGER}, ",
        "#{description,jdbcType=VARCHAR}, #{majorId,jdbcType=BIGINT}, ",
        "#{peopleId,jdbcType=BIGINT}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(TaskPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    int insertSelective(TaskPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    List<TaskPO> selectByExampleWithRowbounds(TaskPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    List<TaskPO> selectByExample(TaskPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskPO record, @Param("example") TaskPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskPO record, @Param("example") TaskPOExample example);
}