package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.TaskSchedulePO;
import com.inmind.mybatis.entity.TaskSchedulePOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface TaskSchedulePOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbg.generated
     */
    long countByExample(TaskSchedulePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbg.generated
     */
    int deleteByExample(TaskSchedulePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbg.generated
     */
    @Insert({
        "insert into task_schedule (relate_id, schedule_type, ",
        "created_time)",
        "values (#{relateId,jdbcType=BIGINT}, #{scheduleType,jdbcType=INTEGER}, ",
        "#{createdTime,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(TaskSchedulePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbg.generated
     */
    int insertSelective(TaskSchedulePO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbg.generated
     */
    List<TaskSchedulePO> selectByExampleWithRowbounds(TaskSchedulePOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbg.generated
     */
    List<TaskSchedulePO> selectByExample(TaskSchedulePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskSchedulePO record, @Param("example") TaskSchedulePOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_schedule
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskSchedulePO record, @Param("example") TaskSchedulePOExample example);
}