package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.TaskCustomRelatedPO;
import com.inmind.mybatis.entity.TaskCustomRelatedPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface TaskCustomRelatedPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_related
     *
     * @mbg.generated
     */
    long countByExample(TaskCustomRelatedPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_related
     *
     * @mbg.generated
     */
    int deleteByExample(TaskCustomRelatedPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_related
     *
     * @mbg.generated
     */
    @Insert({
        "insert into \"task_custom_related\" (task_custom_id, account_id, ",
        "start_at, end_at, ",
        "cycle, repeat_type, ",
        "repeat_stop_at, created_by, ",
        "updated_by, created_at, ",
        "updated_at)",
        "values (#{taskCustomId,jdbcType=BIGINT}, #{accountId,jdbcType=BIGINT}, ",
        "#{startAt,jdbcType=TIMESTAMP}, #{endAt,jdbcType=TIMESTAMP}, ",
        "#{cycle,jdbcType=INTEGER}, #{repeatType,jdbcType=INTEGER}, ",
        "#{repeatStopAt,jdbcType=TIMESTAMP}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(TaskCustomRelatedPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_related
     *
     * @mbg.generated
     */
    int insertSelective(TaskCustomRelatedPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_related
     *
     * @mbg.generated
     */
    List<TaskCustomRelatedPO> selectByExampleWithRowbounds(TaskCustomRelatedPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_related
     *
     * @mbg.generated
     */
    List<TaskCustomRelatedPO> selectByExample(TaskCustomRelatedPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_related
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskCustomRelatedPO record, @Param("example") TaskCustomRelatedPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_related
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskCustomRelatedPO record, @Param("example") TaskCustomRelatedPOExample example);
}