package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.TaskTargetPO;
import com.inmind.mybatis.entity.TaskTargetPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface TaskTargetPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_target
     *
     * @mbg.generated
     */
    long countByExample(TaskTargetPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_target
     *
     * @mbg.generated
     */
    int deleteByExample(TaskTargetPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_target
     *
     * @mbg.generated
     */
    @Insert({
        "insert into task_target (task_id, relate_id, ",
        "people_id, default_co_id, ",
        "default_co_type, target_type, ",
        "interval_time, remind_at, ",
        "pause_at, target_status, ",
        "start_at, dead_line, ",
        "executor_id, task_type, ",
        "description, show_order, ",
        "top_status, is_init_target, ",
        "task_status, created_by, ",
        "updated_by, created_at, ",
        "updated_at, is_remind, ",
        "is_ddl_trigger, is_read, ",
        "sorted_at, task_name)",
        "values (#{taskId,jdbcType=BIGINT}, #{relateId,jdbcType=BIGINT}, ",
        "#{peopleId,jdbcType=BIGINT}, #{defaultCoId,jdbcType=BIGINT}, ",
        "#{defaultCoType,jdbcType=VARCHAR}, #{targetType,jdbcType=INTEGER}, ",
        "#{intervalTime,jdbcType=INTEGER}, #{remindAt,jdbcType=TIMESTAMP}, ",
        "#{pauseAt,jdbcType=TIMESTAMP}, #{targetStatus,jdbcType=INTEGER}, ",
        "#{startAt,jdbcType=TIMESTAMP}, #{deadLine,jdbcType=TIMESTAMP}, ",
        "#{executorId,jdbcType=BIGINT}, #{taskType,jdbcType=INTEGER}, ",
        "#{description,jdbcType=VARCHAR}, #{showOrder,jdbcType=INTEGER}, ",
        "#{topStatus,jdbcType=INTEGER}, #{isInitTarget,jdbcType=INTEGER}, ",
        "#{taskStatus,jdbcType=INTEGER}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{isRemind,jdbcType=INTEGER}, ",
        "#{isDdlTrigger,jdbcType=INTEGER}, #{isRead,jdbcType=INTEGER}, ",
        "#{sortedAt,jdbcType=TIMESTAMP}, #{taskName,jdbcType=VARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(TaskTargetPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_target
     *
     * @mbg.generated
     */
    int insertSelective(TaskTargetPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_target
     *
     * @mbg.generated
     */
    List<TaskTargetPO> selectByExampleWithRowbounds(TaskTargetPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_target
     *
     * @mbg.generated
     */
    List<TaskTargetPO> selectByExample(TaskTargetPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_target
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskTargetPO record, @Param("example") TaskTargetPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_target
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskTargetPO record, @Param("example") TaskTargetPOExample example);
}