package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.TaskQuestionFormPO;
import com.inmind.mybatis.entity.TaskQuestionFormPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface TaskQuestionFormPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question_form
     *
     * @mbg.generated
     */
    long countByExample(TaskQuestionFormPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question_form
     *
     * @mbg.generated
     */
    int deleteByExample(TaskQuestionFormPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question_form
     *
     * @mbg.generated
     */
    @Insert({
        "insert into task_question_form (prop_code, form_type, ",
        "question_id, show_order, ",
        "created_by, updated_by, ",
        "created_at, updated_at)",
        "values (#{propCode,jdbcType=VARCHAR}, #{formType,jdbcType=INTEGER}, ",
        "#{questionId,jdbcType=BIGINT}, #{showOrder,jdbcType=INTEGER}, ",
        "#{createdBy,jdbcType=BIGINT}, #{updatedBy,jdbcType=BIGINT}, ",
        "#{createdAt,jdbcType=TIMESTAMP}, #{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(TaskQuestionFormPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question_form
     *
     * @mbg.generated
     */
    int insertSelective(TaskQuestionFormPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question_form
     *
     * @mbg.generated
     */
    List<TaskQuestionFormPO> selectByExampleWithRowbounds(TaskQuestionFormPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question_form
     *
     * @mbg.generated
     */
    List<TaskQuestionFormPO> selectByExample(TaskQuestionFormPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question_form
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskQuestionFormPO record, @Param("example") TaskQuestionFormPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_question_form
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskQuestionFormPO record, @Param("example") TaskQuestionFormPOExample example);
}