package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.TaskRecommendReportPO;
import com.inmind.mybatis.entity.TaskRecommendReportPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface TaskRecommendReportPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_recommend_report
     *
     * @mbg.generated
     */
    long countByExample(TaskRecommendReportPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_recommend_report
     *
     * @mbg.generated
     */
    int deleteByExample(TaskRecommendReportPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_recommend_report
     *
     * @mbg.generated
     */
    @Insert({
        "insert into task_recommend_report (project_id, task_id, ",
        "resume_id, people_id, ",
        "attachment_id, created_by, ",
        "updated_by, created_at, ",
        "updated_at)",
        "values (#{projectId,jdbcType=INTEGER}, #{taskId,jdbcType=INTEGER}, ",
        "#{resumeId,jdbcType=INTEGER}, #{peopleId,jdbcType=BIGINT}, ",
        "#{attachmentId,jdbcType=INTEGER}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(TaskRecommendReportPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_recommend_report
     *
     * @mbg.generated
     */
    int insertSelective(TaskRecommendReportPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_recommend_report
     *
     * @mbg.generated
     */
    List<TaskRecommendReportPO> selectByExampleWithRowbounds(TaskRecommendReportPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_recommend_report
     *
     * @mbg.generated
     */
    List<TaskRecommendReportPO> selectByExample(TaskRecommendReportPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_recommend_report
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskRecommendReportPO record, @Param("example") TaskRecommendReportPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_recommend_report
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskRecommendReportPO record, @Param("example") TaskRecommendReportPOExample example);
}