package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.TaskCustomAssignPO;
import com.inmind.mybatis.entity.TaskCustomAssignPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface TaskCustomAssignPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_assign
     *
     * @mbg.generated
     */
    long countByExample(TaskCustomAssignPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_assign
     *
     * @mbg.generated
     */
    int deleteByExample(TaskCustomAssignPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_assign
     *
     * @mbg.generated
     */
    @Insert({
        "insert into task_custom_assign (task_custom_id, account_id, ",
        "role, status, created_by, ",
        "updated_by, created_at, ",
        "updated_at)",
        "values (#{taskCustomId,jdbcType=BIGINT}, #{accountId,jdbcType=BIGINT}, ",
        "#{role,jdbcType=INTEGER}, #{status,jdbcType=INTEGER}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(TaskCustomAssignPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_assign
     *
     * @mbg.generated
     */
    int insertSelective(TaskCustomAssignPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_assign
     *
     * @mbg.generated
     */
    List<TaskCustomAssignPO> selectByExampleWithRowbounds(TaskCustomAssignPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_assign
     *
     * @mbg.generated
     */
    List<TaskCustomAssignPO> selectByExample(TaskCustomAssignPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_assign
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TaskCustomAssignPO record, @Param("example") TaskCustomAssignPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table task_custom_assign
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TaskCustomAssignPO record, @Param("example") TaskCustomAssignPOExample example);
}