package com.inmind.mybatis.mapper;

import com.inmind.mybatis.entity.TTaskChainPO;
import com.inmind.mybatis.entity.TTaskChainPOExample;
import java.util.List;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.session.RowBounds;

public interface TTaskChainPOMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_chain
     *
     * @mbg.generated
     */
    long countByExample(TTaskChainPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_chain
     *
     * @mbg.generated
     */
    int deleteByExample(TTaskChainPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_chain
     *
     * @mbg.generated
     */
    @Insert({
        "insert into t_task_chain (company_id, chain_status, ",
        "chain_name, created_by, ",
        "updated_by, created_at, ",
        "updated_at, rules)",
        "values (#{companyId,jdbcType=BIGINT}, #{chainStatus,jdbcType=INTEGER}, ",
        "#{chainName,jdbcType=VARCHAR}, #{createdBy,jdbcType=BIGINT}, ",
        "#{updatedBy,jdbcType=BIGINT}, #{createdAt,jdbcType=TIMESTAMP}, ",
        "#{updatedAt,jdbcType=TIMESTAMP}, #{rules,jdbcType=LONGVARCHAR})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="id", before=false, resultType=Long.class)
    int insert(TTaskChainPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_chain
     *
     * @mbg.generated
     */
    int insertSelective(TTaskChainPO record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_chain
     *
     * @mbg.generated
     */
    List<TTaskChainPO> selectByExampleWithBLOBsWithRowbounds(TTaskChainPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_chain
     *
     * @mbg.generated
     */
    List<TTaskChainPO> selectByExampleWithBLOBs(TTaskChainPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_chain
     *
     * @mbg.generated
     */
    List<TTaskChainPO> selectByExampleWithRowbounds(TTaskChainPOExample example, RowBounds rowBounds);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_chain
     *
     * @mbg.generated
     */
    List<TTaskChainPO> selectByExample(TTaskChainPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_chain
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") TTaskChainPO record, @Param("example") TTaskChainPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_chain
     *
     * @mbg.generated
     */
    int updateByExampleWithBLOBs(@Param("record") TTaskChainPO record, @Param("example") TTaskChainPOExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_task_chain
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") TTaskChainPO record, @Param("example") TTaskChainPOExample example);
}