package com.inmind.mybatis.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContactPOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contact
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contact
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contact
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    public ContactPOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contact
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contact
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNull() {
            addCriterion("company_id is null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIsNotNull() {
            addCriterion("company_id is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyIdEqualTo(Long value) {
            addCriterion("company_id =", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotEqualTo(Long value) {
            addCriterion("company_id <>", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThan(Long value) {
            addCriterion("company_id >", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdGreaterThanOrEqualTo(Long value) {
            addCriterion("company_id >=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThan(Long value) {
            addCriterion("company_id <", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdLessThanOrEqualTo(Long value) {
            addCriterion("company_id <=", value, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdIn(List<Long> values) {
            addCriterion("company_id in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotIn(List<Long> values) {
            addCriterion("company_id not in", values, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdBetween(Long value1, Long value2) {
            addCriterion("company_id between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andCompanyIdNotBetween(Long value1, Long value2) {
            addCriterion("company_id not between", value1, value2, "companyId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdIsNull() {
            addCriterion("people_id is null");
            return (Criteria) this;
        }

        public Criteria andPeopleIdIsNotNull() {
            addCriterion("people_id is not null");
            return (Criteria) this;
        }

        public Criteria andPeopleIdEqualTo(Long value) {
            addCriterion("people_id =", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdNotEqualTo(Long value) {
            addCriterion("people_id <>", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdGreaterThan(Long value) {
            addCriterion("people_id >", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdGreaterThanOrEqualTo(Long value) {
            addCriterion("people_id >=", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdLessThan(Long value) {
            addCriterion("people_id <", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdLessThanOrEqualTo(Long value) {
            addCriterion("people_id <=", value, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdIn(List<Long> values) {
            addCriterion("people_id in", values, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdNotIn(List<Long> values) {
            addCriterion("people_id not in", values, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdBetween(Long value1, Long value2) {
            addCriterion("people_id between", value1, value2, "peopleId");
            return (Criteria) this;
        }

        public Criteria andPeopleIdNotBetween(Long value1, Long value2) {
            addCriterion("people_id not between", value1, value2, "peopleId");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNull() {
            addCriterion("avatar is null");
            return (Criteria) this;
        }

        public Criteria andAvatarIsNotNull() {
            addCriterion("avatar is not null");
            return (Criteria) this;
        }

        public Criteria andAvatarEqualTo(String value) {
            addCriterion("avatar =", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotEqualTo(String value) {
            addCriterion("avatar <>", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThan(String value) {
            addCriterion("avatar >", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarGreaterThanOrEqualTo(String value) {
            addCriterion("avatar >=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThan(String value) {
            addCriterion("avatar <", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLessThanOrEqualTo(String value) {
            addCriterion("avatar <=", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarLike(String value) {
            addCriterion("avatar like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotLike(String value) {
            addCriterion("avatar not like", value, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarIn(List<String> values) {
            addCriterion("avatar in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotIn(List<String> values) {
            addCriterion("avatar not in", values, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarBetween(String value1, String value2) {
            addCriterion("avatar between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andAvatarNotBetween(String value1, String value2) {
            addCriterion("avatar not between", value1, value2, "avatar");
            return (Criteria) this;
        }

        public Criteria andChineseNameIsNull() {
            addCriterion("chinese_name is null");
            return (Criteria) this;
        }

        public Criteria andChineseNameIsNotNull() {
            addCriterion("chinese_name is not null");
            return (Criteria) this;
        }

        public Criteria andChineseNameEqualTo(String value) {
            addCriterion("chinese_name =", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameNotEqualTo(String value) {
            addCriterion("chinese_name <>", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameGreaterThan(String value) {
            addCriterion("chinese_name >", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameGreaterThanOrEqualTo(String value) {
            addCriterion("chinese_name >=", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameLessThan(String value) {
            addCriterion("chinese_name <", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameLessThanOrEqualTo(String value) {
            addCriterion("chinese_name <=", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameLike(String value) {
            addCriterion("chinese_name like", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameNotLike(String value) {
            addCriterion("chinese_name not like", value, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameIn(List<String> values) {
            addCriterion("chinese_name in", values, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameNotIn(List<String> values) {
            addCriterion("chinese_name not in", values, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameBetween(String value1, String value2) {
            addCriterion("chinese_name between", value1, value2, "chineseName");
            return (Criteria) this;
        }

        public Criteria andChineseNameNotBetween(String value1, String value2) {
            addCriterion("chinese_name not between", value1, value2, "chineseName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameIsNull() {
            addCriterion("english_name is null");
            return (Criteria) this;
        }

        public Criteria andEnglishNameIsNotNull() {
            addCriterion("english_name is not null");
            return (Criteria) this;
        }

        public Criteria andEnglishNameEqualTo(String value) {
            addCriterion("english_name =", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotEqualTo(String value) {
            addCriterion("english_name <>", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameGreaterThan(String value) {
            addCriterion("english_name >", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameGreaterThanOrEqualTo(String value) {
            addCriterion("english_name >=", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameLessThan(String value) {
            addCriterion("english_name <", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameLessThanOrEqualTo(String value) {
            addCriterion("english_name <=", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameLike(String value) {
            addCriterion("english_name like", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotLike(String value) {
            addCriterion("english_name not like", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameIn(List<String> values) {
            addCriterion("english_name in", values, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotIn(List<String> values) {
            addCriterion("english_name not in", values, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameBetween(String value1, String value2) {
            addCriterion("english_name between", value1, value2, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotBetween(String value1, String value2) {
            addCriterion("english_name not between", value1, value2, "englishName");
            return (Criteria) this;
        }

        public Criteria andGenderIsNull() {
            addCriterion("gender is null");
            return (Criteria) this;
        }

        public Criteria andGenderIsNotNull() {
            addCriterion("gender is not null");
            return (Criteria) this;
        }

        public Criteria andGenderEqualTo(Integer value) {
            addCriterion("gender =", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotEqualTo(Integer value) {
            addCriterion("gender <>", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThan(Integer value) {
            addCriterion("gender >", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderGreaterThanOrEqualTo(Integer value) {
            addCriterion("gender >=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThan(Integer value) {
            addCriterion("gender <", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderLessThanOrEqualTo(Integer value) {
            addCriterion("gender <=", value, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderIn(List<Integer> values) {
            addCriterion("gender in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotIn(List<Integer> values) {
            addCriterion("gender not in", values, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderBetween(Integer value1, Integer value2) {
            addCriterion("gender between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andGenderNotBetween(Integer value1, Integer value2) {
            addCriterion("gender not between", value1, value2, "gender");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andWorkTelIsNull() {
            addCriterion("work_tel is null");
            return (Criteria) this;
        }

        public Criteria andWorkTelIsNotNull() {
            addCriterion("work_tel is not null");
            return (Criteria) this;
        }

        public Criteria andWorkTelEqualTo(String value) {
            addCriterion("work_tel =", value, "workTel");
            return (Criteria) this;
        }

        public Criteria andWorkTelNotEqualTo(String value) {
            addCriterion("work_tel <>", value, "workTel");
            return (Criteria) this;
        }

        public Criteria andWorkTelGreaterThan(String value) {
            addCriterion("work_tel >", value, "workTel");
            return (Criteria) this;
        }

        public Criteria andWorkTelGreaterThanOrEqualTo(String value) {
            addCriterion("work_tel >=", value, "workTel");
            return (Criteria) this;
        }

        public Criteria andWorkTelLessThan(String value) {
            addCriterion("work_tel <", value, "workTel");
            return (Criteria) this;
        }

        public Criteria andWorkTelLessThanOrEqualTo(String value) {
            addCriterion("work_tel <=", value, "workTel");
            return (Criteria) this;
        }

        public Criteria andWorkTelLike(String value) {
            addCriterion("work_tel like", value, "workTel");
            return (Criteria) this;
        }

        public Criteria andWorkTelNotLike(String value) {
            addCriterion("work_tel not like", value, "workTel");
            return (Criteria) this;
        }

        public Criteria andWorkTelIn(List<String> values) {
            addCriterion("work_tel in", values, "workTel");
            return (Criteria) this;
        }

        public Criteria andWorkTelNotIn(List<String> values) {
            addCriterion("work_tel not in", values, "workTel");
            return (Criteria) this;
        }

        public Criteria andWorkTelBetween(String value1, String value2) {
            addCriterion("work_tel between", value1, value2, "workTel");
            return (Criteria) this;
        }

        public Criteria andWorkTelNotBetween(String value1, String value2) {
            addCriterion("work_tel not between", value1, value2, "workTel");
            return (Criteria) this;
        }

        public Criteria andWorkPhoneIsNull() {
            addCriterion("work_phone is null");
            return (Criteria) this;
        }

        public Criteria andWorkPhoneIsNotNull() {
            addCriterion("work_phone is not null");
            return (Criteria) this;
        }

        public Criteria andWorkPhoneEqualTo(String value) {
            addCriterion("work_phone =", value, "workPhone");
            return (Criteria) this;
        }

        public Criteria andWorkPhoneNotEqualTo(String value) {
            addCriterion("work_phone <>", value, "workPhone");
            return (Criteria) this;
        }

        public Criteria andWorkPhoneGreaterThan(String value) {
            addCriterion("work_phone >", value, "workPhone");
            return (Criteria) this;
        }

        public Criteria andWorkPhoneGreaterThanOrEqualTo(String value) {
            addCriterion("work_phone >=", value, "workPhone");
            return (Criteria) this;
        }

        public Criteria andWorkPhoneLessThan(String value) {
            addCriterion("work_phone <", value, "workPhone");
            return (Criteria) this;
        }

        public Criteria andWorkPhoneLessThanOrEqualTo(String value) {
            addCriterion("work_phone <=", value, "workPhone");
            return (Criteria) this;
        }

        public Criteria andWorkPhoneLike(String value) {
            addCriterion("work_phone like", value, "workPhone");
            return (Criteria) this;
        }

        public Criteria andWorkPhoneNotLike(String value) {
            addCriterion("work_phone not like", value, "workPhone");
            return (Criteria) this;
        }

        public Criteria andWorkPhoneIn(List<String> values) {
            addCriterion("work_phone in", values, "workPhone");
            return (Criteria) this;
        }

        public Criteria andWorkPhoneNotIn(List<String> values) {
            addCriterion("work_phone not in", values, "workPhone");
            return (Criteria) this;
        }

        public Criteria andWorkPhoneBetween(String value1, String value2) {
            addCriterion("work_phone between", value1, value2, "workPhone");
            return (Criteria) this;
        }

        public Criteria andWorkPhoneNotBetween(String value1, String value2) {
            addCriterion("work_phone not between", value1, value2, "workPhone");
            return (Criteria) this;
        }

        public Criteria andOtherTelIsNull() {
            addCriterion("other_tel is null");
            return (Criteria) this;
        }

        public Criteria andOtherTelIsNotNull() {
            addCriterion("other_tel is not null");
            return (Criteria) this;
        }

        public Criteria andOtherTelEqualTo(String value) {
            addCriterion("other_tel =", value, "otherTel");
            return (Criteria) this;
        }

        public Criteria andOtherTelNotEqualTo(String value) {
            addCriterion("other_tel <>", value, "otherTel");
            return (Criteria) this;
        }

        public Criteria andOtherTelGreaterThan(String value) {
            addCriterion("other_tel >", value, "otherTel");
            return (Criteria) this;
        }

        public Criteria andOtherTelGreaterThanOrEqualTo(String value) {
            addCriterion("other_tel >=", value, "otherTel");
            return (Criteria) this;
        }

        public Criteria andOtherTelLessThan(String value) {
            addCriterion("other_tel <", value, "otherTel");
            return (Criteria) this;
        }

        public Criteria andOtherTelLessThanOrEqualTo(String value) {
            addCriterion("other_tel <=", value, "otherTel");
            return (Criteria) this;
        }

        public Criteria andOtherTelLike(String value) {
            addCriterion("other_tel like", value, "otherTel");
            return (Criteria) this;
        }

        public Criteria andOtherTelNotLike(String value) {
            addCriterion("other_tel not like", value, "otherTel");
            return (Criteria) this;
        }

        public Criteria andOtherTelIn(List<String> values) {
            addCriterion("other_tel in", values, "otherTel");
            return (Criteria) this;
        }

        public Criteria andOtherTelNotIn(List<String> values) {
            addCriterion("other_tel not in", values, "otherTel");
            return (Criteria) this;
        }

        public Criteria andOtherTelBetween(String value1, String value2) {
            addCriterion("other_tel between", value1, value2, "otherTel");
            return (Criteria) this;
        }

        public Criteria andOtherTelNotBetween(String value1, String value2) {
            addCriterion("other_tel not between", value1, value2, "otherTel");
            return (Criteria) this;
        }

        public Criteria andPrivateEmailIsNull() {
            addCriterion("private_email is null");
            return (Criteria) this;
        }

        public Criteria andPrivateEmailIsNotNull() {
            addCriterion("private_email is not null");
            return (Criteria) this;
        }

        public Criteria andPrivateEmailEqualTo(String value) {
            addCriterion("private_email =", value, "privateEmail");
            return (Criteria) this;
        }

        public Criteria andPrivateEmailNotEqualTo(String value) {
            addCriterion("private_email <>", value, "privateEmail");
            return (Criteria) this;
        }

        public Criteria andPrivateEmailGreaterThan(String value) {
            addCriterion("private_email >", value, "privateEmail");
            return (Criteria) this;
        }

        public Criteria andPrivateEmailGreaterThanOrEqualTo(String value) {
            addCriterion("private_email >=", value, "privateEmail");
            return (Criteria) this;
        }

        public Criteria andPrivateEmailLessThan(String value) {
            addCriterion("private_email <", value, "privateEmail");
            return (Criteria) this;
        }

        public Criteria andPrivateEmailLessThanOrEqualTo(String value) {
            addCriterion("private_email <=", value, "privateEmail");
            return (Criteria) this;
        }

        public Criteria andPrivateEmailLike(String value) {
            addCriterion("private_email like", value, "privateEmail");
            return (Criteria) this;
        }

        public Criteria andPrivateEmailNotLike(String value) {
            addCriterion("private_email not like", value, "privateEmail");
            return (Criteria) this;
        }

        public Criteria andPrivateEmailIn(List<String> values) {
            addCriterion("private_email in", values, "privateEmail");
            return (Criteria) this;
        }

        public Criteria andPrivateEmailNotIn(List<String> values) {
            addCriterion("private_email not in", values, "privateEmail");
            return (Criteria) this;
        }

        public Criteria andPrivateEmailBetween(String value1, String value2) {
            addCriterion("private_email between", value1, value2, "privateEmail");
            return (Criteria) this;
        }

        public Criteria andPrivateEmailNotBetween(String value1, String value2) {
            addCriterion("private_email not between", value1, value2, "privateEmail");
            return (Criteria) this;
        }

        public Criteria andWorkEmailIsNull() {
            addCriterion("work_email is null");
            return (Criteria) this;
        }

        public Criteria andWorkEmailIsNotNull() {
            addCriterion("work_email is not null");
            return (Criteria) this;
        }

        public Criteria andWorkEmailEqualTo(String value) {
            addCriterion("work_email =", value, "workEmail");
            return (Criteria) this;
        }

        public Criteria andWorkEmailNotEqualTo(String value) {
            addCriterion("work_email <>", value, "workEmail");
            return (Criteria) this;
        }

        public Criteria andWorkEmailGreaterThan(String value) {
            addCriterion("work_email >", value, "workEmail");
            return (Criteria) this;
        }

        public Criteria andWorkEmailGreaterThanOrEqualTo(String value) {
            addCriterion("work_email >=", value, "workEmail");
            return (Criteria) this;
        }

        public Criteria andWorkEmailLessThan(String value) {
            addCriterion("work_email <", value, "workEmail");
            return (Criteria) this;
        }

        public Criteria andWorkEmailLessThanOrEqualTo(String value) {
            addCriterion("work_email <=", value, "workEmail");
            return (Criteria) this;
        }

        public Criteria andWorkEmailLike(String value) {
            addCriterion("work_email like", value, "workEmail");
            return (Criteria) this;
        }

        public Criteria andWorkEmailNotLike(String value) {
            addCriterion("work_email not like", value, "workEmail");
            return (Criteria) this;
        }

        public Criteria andWorkEmailIn(List<String> values) {
            addCriterion("work_email in", values, "workEmail");
            return (Criteria) this;
        }

        public Criteria andWorkEmailNotIn(List<String> values) {
            addCriterion("work_email not in", values, "workEmail");
            return (Criteria) this;
        }

        public Criteria andWorkEmailBetween(String value1, String value2) {
            addCriterion("work_email between", value1, value2, "workEmail");
            return (Criteria) this;
        }

        public Criteria andWorkEmailNotBetween(String value1, String value2) {
            addCriterion("work_email not between", value1, value2, "workEmail");
            return (Criteria) this;
        }

        public Criteria andOtherEmailIsNull() {
            addCriterion("other_email is null");
            return (Criteria) this;
        }

        public Criteria andOtherEmailIsNotNull() {
            addCriterion("other_email is not null");
            return (Criteria) this;
        }

        public Criteria andOtherEmailEqualTo(String value) {
            addCriterion("other_email =", value, "otherEmail");
            return (Criteria) this;
        }

        public Criteria andOtherEmailNotEqualTo(String value) {
            addCriterion("other_email <>", value, "otherEmail");
            return (Criteria) this;
        }

        public Criteria andOtherEmailGreaterThan(String value) {
            addCriterion("other_email >", value, "otherEmail");
            return (Criteria) this;
        }

        public Criteria andOtherEmailGreaterThanOrEqualTo(String value) {
            addCriterion("other_email >=", value, "otherEmail");
            return (Criteria) this;
        }

        public Criteria andOtherEmailLessThan(String value) {
            addCriterion("other_email <", value, "otherEmail");
            return (Criteria) this;
        }

        public Criteria andOtherEmailLessThanOrEqualTo(String value) {
            addCriterion("other_email <=", value, "otherEmail");
            return (Criteria) this;
        }

        public Criteria andOtherEmailLike(String value) {
            addCriterion("other_email like", value, "otherEmail");
            return (Criteria) this;
        }

        public Criteria andOtherEmailNotLike(String value) {
            addCriterion("other_email not like", value, "otherEmail");
            return (Criteria) this;
        }

        public Criteria andOtherEmailIn(List<String> values) {
            addCriterion("other_email in", values, "otherEmail");
            return (Criteria) this;
        }

        public Criteria andOtherEmailNotIn(List<String> values) {
            addCriterion("other_email not in", values, "otherEmail");
            return (Criteria) this;
        }

        public Criteria andOtherEmailBetween(String value1, String value2) {
            addCriterion("other_email between", value1, value2, "otherEmail");
            return (Criteria) this;
        }

        public Criteria andOtherEmailNotBetween(String value1, String value2) {
            addCriterion("other_email not between", value1, value2, "otherEmail");
            return (Criteria) this;
        }

        public Criteria andWechatNoIsNull() {
            addCriterion("wechat_no is null");
            return (Criteria) this;
        }

        public Criteria andWechatNoIsNotNull() {
            addCriterion("wechat_no is not null");
            return (Criteria) this;
        }

        public Criteria andWechatNoEqualTo(String value) {
            addCriterion("wechat_no =", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoNotEqualTo(String value) {
            addCriterion("wechat_no <>", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoGreaterThan(String value) {
            addCriterion("wechat_no >", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoGreaterThanOrEqualTo(String value) {
            addCriterion("wechat_no >=", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoLessThan(String value) {
            addCriterion("wechat_no <", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoLessThanOrEqualTo(String value) {
            addCriterion("wechat_no <=", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoLike(String value) {
            addCriterion("wechat_no like", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoNotLike(String value) {
            addCriterion("wechat_no not like", value, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoIn(List<String> values) {
            addCriterion("wechat_no in", values, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoNotIn(List<String> values) {
            addCriterion("wechat_no not in", values, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoBetween(String value1, String value2) {
            addCriterion("wechat_no between", value1, value2, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andWechatNoNotBetween(String value1, String value2) {
            addCriterion("wechat_no not between", value1, value2, "wechatNo");
            return (Criteria) this;
        }

        public Criteria andQqNoIsNull() {
            addCriterion("qq_no is null");
            return (Criteria) this;
        }

        public Criteria andQqNoIsNotNull() {
            addCriterion("qq_no is not null");
            return (Criteria) this;
        }

        public Criteria andQqNoEqualTo(String value) {
            addCriterion("qq_no =", value, "qqNo");
            return (Criteria) this;
        }

        public Criteria andQqNoNotEqualTo(String value) {
            addCriterion("qq_no <>", value, "qqNo");
            return (Criteria) this;
        }

        public Criteria andQqNoGreaterThan(String value) {
            addCriterion("qq_no >", value, "qqNo");
            return (Criteria) this;
        }

        public Criteria andQqNoGreaterThanOrEqualTo(String value) {
            addCriterion("qq_no >=", value, "qqNo");
            return (Criteria) this;
        }

        public Criteria andQqNoLessThan(String value) {
            addCriterion("qq_no <", value, "qqNo");
            return (Criteria) this;
        }

        public Criteria andQqNoLessThanOrEqualTo(String value) {
            addCriterion("qq_no <=", value, "qqNo");
            return (Criteria) this;
        }

        public Criteria andQqNoLike(String value) {
            addCriterion("qq_no like", value, "qqNo");
            return (Criteria) this;
        }

        public Criteria andQqNoNotLike(String value) {
            addCriterion("qq_no not like", value, "qqNo");
            return (Criteria) this;
        }

        public Criteria andQqNoIn(List<String> values) {
            addCriterion("qq_no in", values, "qqNo");
            return (Criteria) this;
        }

        public Criteria andQqNoNotIn(List<String> values) {
            addCriterion("qq_no not in", values, "qqNo");
            return (Criteria) this;
        }

        public Criteria andQqNoBetween(String value1, String value2) {
            addCriterion("qq_no between", value1, value2, "qqNo");
            return (Criteria) this;
        }

        public Criteria andQqNoNotBetween(String value1, String value2) {
            addCriterion("qq_no not between", value1, value2, "qqNo");
            return (Criteria) this;
        }

        public Criteria andWeiboIsNull() {
            addCriterion("weibo is null");
            return (Criteria) this;
        }

        public Criteria andWeiboIsNotNull() {
            addCriterion("weibo is not null");
            return (Criteria) this;
        }

        public Criteria andWeiboEqualTo(String value) {
            addCriterion("weibo =", value, "weibo");
            return (Criteria) this;
        }

        public Criteria andWeiboNotEqualTo(String value) {
            addCriterion("weibo <>", value, "weibo");
            return (Criteria) this;
        }

        public Criteria andWeiboGreaterThan(String value) {
            addCriterion("weibo >", value, "weibo");
            return (Criteria) this;
        }

        public Criteria andWeiboGreaterThanOrEqualTo(String value) {
            addCriterion("weibo >=", value, "weibo");
            return (Criteria) this;
        }

        public Criteria andWeiboLessThan(String value) {
            addCriterion("weibo <", value, "weibo");
            return (Criteria) this;
        }

        public Criteria andWeiboLessThanOrEqualTo(String value) {
            addCriterion("weibo <=", value, "weibo");
            return (Criteria) this;
        }

        public Criteria andWeiboLike(String value) {
            addCriterion("weibo like", value, "weibo");
            return (Criteria) this;
        }

        public Criteria andWeiboNotLike(String value) {
            addCriterion("weibo not like", value, "weibo");
            return (Criteria) this;
        }

        public Criteria andWeiboIn(List<String> values) {
            addCriterion("weibo in", values, "weibo");
            return (Criteria) this;
        }

        public Criteria andWeiboNotIn(List<String> values) {
            addCriterion("weibo not in", values, "weibo");
            return (Criteria) this;
        }

        public Criteria andWeiboBetween(String value1, String value2) {
            addCriterion("weibo between", value1, value2, "weibo");
            return (Criteria) this;
        }

        public Criteria andWeiboNotBetween(String value1, String value2) {
            addCriterion("weibo not between", value1, value2, "weibo");
            return (Criteria) this;
        }

        public Criteria andContactIntegrityIsNull() {
            addCriterion("contact_integrity is null");
            return (Criteria) this;
        }

        public Criteria andContactIntegrityIsNotNull() {
            addCriterion("contact_integrity is not null");
            return (Criteria) this;
        }

        public Criteria andContactIntegrityEqualTo(BigDecimal value) {
            addCriterion("contact_integrity =", value, "contactIntegrity");
            return (Criteria) this;
        }

        public Criteria andContactIntegrityNotEqualTo(BigDecimal value) {
            addCriterion("contact_integrity <>", value, "contactIntegrity");
            return (Criteria) this;
        }

        public Criteria andContactIntegrityGreaterThan(BigDecimal value) {
            addCriterion("contact_integrity >", value, "contactIntegrity");
            return (Criteria) this;
        }

        public Criteria andContactIntegrityGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("contact_integrity >=", value, "contactIntegrity");
            return (Criteria) this;
        }

        public Criteria andContactIntegrityLessThan(BigDecimal value) {
            addCriterion("contact_integrity <", value, "contactIntegrity");
            return (Criteria) this;
        }

        public Criteria andContactIntegrityLessThanOrEqualTo(BigDecimal value) {
            addCriterion("contact_integrity <=", value, "contactIntegrity");
            return (Criteria) this;
        }

        public Criteria andContactIntegrityIn(List<BigDecimal> values) {
            addCriterion("contact_integrity in", values, "contactIntegrity");
            return (Criteria) this;
        }

        public Criteria andContactIntegrityNotIn(List<BigDecimal> values) {
            addCriterion("contact_integrity not in", values, "contactIntegrity");
            return (Criteria) this;
        }

        public Criteria andContactIntegrityBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("contact_integrity between", value1, value2, "contactIntegrity");
            return (Criteria) this;
        }

        public Criteria andContactIntegrityNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("contact_integrity not between", value1, value2, "contactIntegrity");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNull() {
            addCriterion("org_id is null");
            return (Criteria) this;
        }

        public Criteria andOrgIdIsNotNull() {
            addCriterion("org_id is not null");
            return (Criteria) this;
        }

        public Criteria andOrgIdEqualTo(Long value) {
            addCriterion("org_id =", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotEqualTo(Long value) {
            addCriterion("org_id <>", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThan(Long value) {
            addCriterion("org_id >", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdGreaterThanOrEqualTo(Long value) {
            addCriterion("org_id >=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThan(Long value) {
            addCriterion("org_id <", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdLessThanOrEqualTo(Long value) {
            addCriterion("org_id <=", value, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdIn(List<Long> values) {
            addCriterion("org_id in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotIn(List<Long> values) {
            addCriterion("org_id not in", values, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdBetween(Long value1, Long value2) {
            addCriterion("org_id between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgIdNotBetween(Long value1, Long value2) {
            addCriterion("org_id not between", value1, value2, "orgId");
            return (Criteria) this;
        }

        public Criteria andOrgNameIsNull() {
            addCriterion("org_name is null");
            return (Criteria) this;
        }

        public Criteria andOrgNameIsNotNull() {
            addCriterion("org_name is not null");
            return (Criteria) this;
        }

        public Criteria andOrgNameEqualTo(String value) {
            addCriterion("org_name =", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotEqualTo(String value) {
            addCriterion("org_name <>", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameGreaterThan(String value) {
            addCriterion("org_name >", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameGreaterThanOrEqualTo(String value) {
            addCriterion("org_name >=", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLessThan(String value) {
            addCriterion("org_name <", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLessThanOrEqualTo(String value) {
            addCriterion("org_name <=", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameLike(String value) {
            addCriterion("org_name like", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotLike(String value) {
            addCriterion("org_name not like", value, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameIn(List<String> values) {
            addCriterion("org_name in", values, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotIn(List<String> values) {
            addCriterion("org_name not in", values, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameBetween(String value1, String value2) {
            addCriterion("org_name between", value1, value2, "orgName");
            return (Criteria) this;
        }

        public Criteria andOrgNameNotBetween(String value1, String value2) {
            addCriterion("org_name not between", value1, value2, "orgName");
            return (Criteria) this;
        }

        public Criteria andIndustryIsNull() {
            addCriterion("industry is null");
            return (Criteria) this;
        }

        public Criteria andIndustryIsNotNull() {
            addCriterion("industry is not null");
            return (Criteria) this;
        }

        public Criteria andIndustryEqualTo(Integer value) {
            addCriterion("industry =", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotEqualTo(Integer value) {
            addCriterion("industry <>", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryGreaterThan(Integer value) {
            addCriterion("industry >", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryGreaterThanOrEqualTo(Integer value) {
            addCriterion("industry >=", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryLessThan(Integer value) {
            addCriterion("industry <", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryLessThanOrEqualTo(Integer value) {
            addCriterion("industry <=", value, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryIn(List<Integer> values) {
            addCriterion("industry in", values, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotIn(List<Integer> values) {
            addCriterion("industry not in", values, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryBetween(Integer value1, Integer value2) {
            addCriterion("industry between", value1, value2, "industry");
            return (Criteria) this;
        }

        public Criteria andIndustryNotBetween(Integer value1, Integer value2) {
            addCriterion("industry not between", value1, value2, "industry");
            return (Criteria) this;
        }

        public Criteria andPositionIsNull() {
            addCriterion("position is null");
            return (Criteria) this;
        }

        public Criteria andPositionIsNotNull() {
            addCriterion("position is not null");
            return (Criteria) this;
        }

        public Criteria andPositionEqualTo(String value) {
            addCriterion("position =", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotEqualTo(String value) {
            addCriterion("position <>", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThan(String value) {
            addCriterion("position >", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionGreaterThanOrEqualTo(String value) {
            addCriterion("position >=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThan(String value) {
            addCriterion("position <", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLessThanOrEqualTo(String value) {
            addCriterion("position <=", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionLike(String value) {
            addCriterion("position like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotLike(String value) {
            addCriterion("position not like", value, "position");
            return (Criteria) this;
        }

        public Criteria andPositionIn(List<String> values) {
            addCriterion("position in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotIn(List<String> values) {
            addCriterion("position not in", values, "position");
            return (Criteria) this;
        }

        public Criteria andPositionBetween(String value1, String value2) {
            addCriterion("position between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andPositionNotBetween(String value1, String value2) {
            addCriterion("position not between", value1, value2, "position");
            return (Criteria) this;
        }

        public Criteria andContactTypeIsNull() {
            addCriterion("contact_type is null");
            return (Criteria) this;
        }

        public Criteria andContactTypeIsNotNull() {
            addCriterion("contact_type is not null");
            return (Criteria) this;
        }

        public Criteria andContactTypeEqualTo(Integer value) {
            addCriterion("contact_type =", value, "contactType");
            return (Criteria) this;
        }

        public Criteria andContactTypeNotEqualTo(Integer value) {
            addCriterion("contact_type <>", value, "contactType");
            return (Criteria) this;
        }

        public Criteria andContactTypeGreaterThan(Integer value) {
            addCriterion("contact_type >", value, "contactType");
            return (Criteria) this;
        }

        public Criteria andContactTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("contact_type >=", value, "contactType");
            return (Criteria) this;
        }

        public Criteria andContactTypeLessThan(Integer value) {
            addCriterion("contact_type <", value, "contactType");
            return (Criteria) this;
        }

        public Criteria andContactTypeLessThanOrEqualTo(Integer value) {
            addCriterion("contact_type <=", value, "contactType");
            return (Criteria) this;
        }

        public Criteria andContactTypeIn(List<Integer> values) {
            addCriterion("contact_type in", values, "contactType");
            return (Criteria) this;
        }

        public Criteria andContactTypeNotIn(List<Integer> values) {
            addCriterion("contact_type not in", values, "contactType");
            return (Criteria) this;
        }

        public Criteria andContactTypeBetween(Integer value1, Integer value2) {
            addCriterion("contact_type between", value1, value2, "contactType");
            return (Criteria) this;
        }

        public Criteria andContactTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("contact_type not between", value1, value2, "contactType");
            return (Criteria) this;
        }

        public Criteria andRecruitLocationIdsIsNull() {
            addCriterion("recruit_location_ids is null");
            return (Criteria) this;
        }

        public Criteria andRecruitLocationIdsIsNotNull() {
            addCriterion("recruit_location_ids is not null");
            return (Criteria) this;
        }

        public Criteria andRecruitLocationIdsEqualTo(String value) {
            addCriterion("recruit_location_ids =", value, "recruitLocationIds");
            return (Criteria) this;
        }

        public Criteria andRecruitLocationIdsNotEqualTo(String value) {
            addCriterion("recruit_location_ids <>", value, "recruitLocationIds");
            return (Criteria) this;
        }

        public Criteria andRecruitLocationIdsGreaterThan(String value) {
            addCriterion("recruit_location_ids >", value, "recruitLocationIds");
            return (Criteria) this;
        }

        public Criteria andRecruitLocationIdsGreaterThanOrEqualTo(String value) {
            addCriterion("recruit_location_ids >=", value, "recruitLocationIds");
            return (Criteria) this;
        }

        public Criteria andRecruitLocationIdsLessThan(String value) {
            addCriterion("recruit_location_ids <", value, "recruitLocationIds");
            return (Criteria) this;
        }

        public Criteria andRecruitLocationIdsLessThanOrEqualTo(String value) {
            addCriterion("recruit_location_ids <=", value, "recruitLocationIds");
            return (Criteria) this;
        }

        public Criteria andRecruitLocationIdsLike(String value) {
            addCriterion("recruit_location_ids like", value, "recruitLocationIds");
            return (Criteria) this;
        }

        public Criteria andRecruitLocationIdsNotLike(String value) {
            addCriterion("recruit_location_ids not like", value, "recruitLocationIds");
            return (Criteria) this;
        }

        public Criteria andRecruitLocationIdsIn(List<String> values) {
            addCriterion("recruit_location_ids in", values, "recruitLocationIds");
            return (Criteria) this;
        }

        public Criteria andRecruitLocationIdsNotIn(List<String> values) {
            addCriterion("recruit_location_ids not in", values, "recruitLocationIds");
            return (Criteria) this;
        }

        public Criteria andRecruitLocationIdsBetween(String value1, String value2) {
            addCriterion("recruit_location_ids between", value1, value2, "recruitLocationIds");
            return (Criteria) this;
        }

        public Criteria andRecruitLocationIdsNotBetween(String value1, String value2) {
            addCriterion("recruit_location_ids not between", value1, value2, "recruitLocationIds");
            return (Criteria) this;
        }

        public Criteria andRecruitFunctionsIsNull() {
            addCriterion("recruit_functions is null");
            return (Criteria) this;
        }

        public Criteria andRecruitFunctionsIsNotNull() {
            addCriterion("recruit_functions is not null");
            return (Criteria) this;
        }

        public Criteria andRecruitFunctionsEqualTo(String value) {
            addCriterion("recruit_functions =", value, "recruitFunctions");
            return (Criteria) this;
        }

        public Criteria andRecruitFunctionsNotEqualTo(String value) {
            addCriterion("recruit_functions <>", value, "recruitFunctions");
            return (Criteria) this;
        }

        public Criteria andRecruitFunctionsGreaterThan(String value) {
            addCriterion("recruit_functions >", value, "recruitFunctions");
            return (Criteria) this;
        }

        public Criteria andRecruitFunctionsGreaterThanOrEqualTo(String value) {
            addCriterion("recruit_functions >=", value, "recruitFunctions");
            return (Criteria) this;
        }

        public Criteria andRecruitFunctionsLessThan(String value) {
            addCriterion("recruit_functions <", value, "recruitFunctions");
            return (Criteria) this;
        }

        public Criteria andRecruitFunctionsLessThanOrEqualTo(String value) {
            addCriterion("recruit_functions <=", value, "recruitFunctions");
            return (Criteria) this;
        }

        public Criteria andRecruitFunctionsLike(String value) {
            addCriterion("recruit_functions like", value, "recruitFunctions");
            return (Criteria) this;
        }

        public Criteria andRecruitFunctionsNotLike(String value) {
            addCriterion("recruit_functions not like", value, "recruitFunctions");
            return (Criteria) this;
        }

        public Criteria andRecruitFunctionsIn(List<String> values) {
            addCriterion("recruit_functions in", values, "recruitFunctions");
            return (Criteria) this;
        }

        public Criteria andRecruitFunctionsNotIn(List<String> values) {
            addCriterion("recruit_functions not in", values, "recruitFunctions");
            return (Criteria) this;
        }

        public Criteria andRecruitFunctionsBetween(String value1, String value2) {
            addCriterion("recruit_functions between", value1, value2, "recruitFunctions");
            return (Criteria) this;
        }

        public Criteria andRecruitFunctionsNotBetween(String value1, String value2) {
            addCriterion("recruit_functions not between", value1, value2, "recruitFunctions");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNull() {
            addCriterion("owner_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNotNull() {
            addCriterion("owner_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdEqualTo(Long value) {
            addCriterion("owner_id =", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotEqualTo(Long value) {
            addCriterion("owner_id <>", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThan(Long value) {
            addCriterion("owner_id >", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("owner_id >=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThan(Long value) {
            addCriterion("owner_id <", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThanOrEqualTo(Long value) {
            addCriterion("owner_id <=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIn(List<Long> values) {
            addCriterion("owner_id in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotIn(List<Long> values) {
            addCriterion("owner_id not in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdBetween(Long value1, Long value2) {
            addCriterion("owner_id between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotBetween(Long value1, Long value2) {
            addCriterion("owner_id not between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(Long value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(Long value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(Long value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(Long value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(Long value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<Long> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<Long> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(Long value1, Long value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(Long value1, Long value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("updated_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("updated_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(Long value) {
            addCriterion("updated_by =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(Long value) {
            addCriterion("updated_by <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(Long value) {
            addCriterion("updated_by >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(Long value) {
            addCriterion("updated_by >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(Long value) {
            addCriterion("updated_by <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(Long value) {
            addCriterion("updated_by <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<Long> values) {
            addCriterion("updated_by in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<Long> values) {
            addCriterion("updated_by not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(Long value1, Long value2) {
            addCriterion("updated_by between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(Long value1, Long value2) {
            addCriterion("updated_by not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andLatestContactAtIsNull() {
            addCriterion("latest_contact_at is null");
            return (Criteria) this;
        }

        public Criteria andLatestContactAtIsNotNull() {
            addCriterion("latest_contact_at is not null");
            return (Criteria) this;
        }

        public Criteria andLatestContactAtEqualTo(Date value) {
            addCriterion("latest_contact_at =", value, "latestContactAt");
            return (Criteria) this;
        }

        public Criteria andLatestContactAtNotEqualTo(Date value) {
            addCriterion("latest_contact_at <>", value, "latestContactAt");
            return (Criteria) this;
        }

        public Criteria andLatestContactAtGreaterThan(Date value) {
            addCriterion("latest_contact_at >", value, "latestContactAt");
            return (Criteria) this;
        }

        public Criteria andLatestContactAtGreaterThanOrEqualTo(Date value) {
            addCriterion("latest_contact_at >=", value, "latestContactAt");
            return (Criteria) this;
        }

        public Criteria andLatestContactAtLessThan(Date value) {
            addCriterion("latest_contact_at <", value, "latestContactAt");
            return (Criteria) this;
        }

        public Criteria andLatestContactAtLessThanOrEqualTo(Date value) {
            addCriterion("latest_contact_at <=", value, "latestContactAt");
            return (Criteria) this;
        }

        public Criteria andLatestContactAtIn(List<Date> values) {
            addCriterion("latest_contact_at in", values, "latestContactAt");
            return (Criteria) this;
        }

        public Criteria andLatestContactAtNotIn(List<Date> values) {
            addCriterion("latest_contact_at not in", values, "latestContactAt");
            return (Criteria) this;
        }

        public Criteria andLatestContactAtBetween(Date value1, Date value2) {
            addCriterion("latest_contact_at between", value1, value2, "latestContactAt");
            return (Criteria) this;
        }

        public Criteria andLatestContactAtNotBetween(Date value1, Date value2) {
            addCriterion("latest_contact_at not between", value1, value2, "latestContactAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contact
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contact
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}