package com.inmind.mybatis.entity;

import java.util.Date;

public class OperationConfigPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_config.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_config.table_name
     *
     * @mbg.generated
     */
    private String tableName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_config.busi_name
     *
     * @mbg.generated
     */
    private String busiName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_config.created_by
     *
     * @mbg.generated
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_config.updated_by
     *
     * @mbg.generated
     */
    private Long updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_config.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column operation_config.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_config.id
     *
     * @return the value of operation_config.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_config.id
     *
     * @param id the value for operation_config.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_config.table_name
     *
     * @return the value of operation_config.table_name
     *
     * @mbg.generated
     */
    public String getTableName() {
        return tableName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_config.table_name
     *
     * @param tableName the value for operation_config.table_name
     *
     * @mbg.generated
     */
    public void setTableName(String tableName) {
        this.tableName = tableName == null ? null : tableName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_config.busi_name
     *
     * @return the value of operation_config.busi_name
     *
     * @mbg.generated
     */
    public String getBusiName() {
        return busiName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_config.busi_name
     *
     * @param busiName the value for operation_config.busi_name
     *
     * @mbg.generated
     */
    public void setBusiName(String busiName) {
        this.busiName = busiName == null ? null : busiName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_config.created_by
     *
     * @return the value of operation_config.created_by
     *
     * @mbg.generated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_config.created_by
     *
     * @param createdBy the value for operation_config.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_config.updated_by
     *
     * @return the value of operation_config.updated_by
     *
     * @mbg.generated
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_config.updated_by
     *
     * @param updatedBy the value for operation_config.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_config.created_at
     *
     * @return the value of operation_config.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_config.created_at
     *
     * @param createdAt the value for operation_config.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column operation_config.updated_at
     *
     * @return the value of operation_config.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column operation_config.updated_at
     *
     * @param updatedAt the value for operation_config.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}