package com.inmind.mybatis.entity;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class OrganizationPOExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organization
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organization
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table organization
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    public OrganizationPOExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table organization
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table organization
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andNameIsNull() {
            addCriterion("name is null");
            return (Criteria) this;
        }

        public Criteria andNameIsNotNull() {
            addCriterion("name is not null");
            return (Criteria) this;
        }

        public Criteria andNameEqualTo(String value) {
            addCriterion("name =", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotEqualTo(String value) {
            addCriterion("name <>", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThan(String value) {
            addCriterion("name >", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameGreaterThanOrEqualTo(String value) {
            addCriterion("name >=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThan(String value) {
            addCriterion("name <", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLessThanOrEqualTo(String value) {
            addCriterion("name <=", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameLike(String value) {
            addCriterion("name like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotLike(String value) {
            addCriterion("name not like", value, "name");
            return (Criteria) this;
        }

        public Criteria andNameIn(List<String> values) {
            addCriterion("name in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotIn(List<String> values) {
            addCriterion("name not in", values, "name");
            return (Criteria) this;
        }

        public Criteria andNameBetween(String value1, String value2) {
            addCriterion("name between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andNameNotBetween(String value1, String value2) {
            addCriterion("name not between", value1, value2, "name");
            return (Criteria) this;
        }

        public Criteria andSimpleNameIsNull() {
            addCriterion("simple_name is null");
            return (Criteria) this;
        }

        public Criteria andSimpleNameIsNotNull() {
            addCriterion("simple_name is not null");
            return (Criteria) this;
        }

        public Criteria andSimpleNameEqualTo(String value) {
            addCriterion("simple_name =", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameNotEqualTo(String value) {
            addCriterion("simple_name <>", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameGreaterThan(String value) {
            addCriterion("simple_name >", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameGreaterThanOrEqualTo(String value) {
            addCriterion("simple_name >=", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameLessThan(String value) {
            addCriterion("simple_name <", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameLessThanOrEqualTo(String value) {
            addCriterion("simple_name <=", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameLike(String value) {
            addCriterion("simple_name like", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameNotLike(String value) {
            addCriterion("simple_name not like", value, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameIn(List<String> values) {
            addCriterion("simple_name in", values, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameNotIn(List<String> values) {
            addCriterion("simple_name not in", values, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameBetween(String value1, String value2) {
            addCriterion("simple_name between", value1, value2, "simpleName");
            return (Criteria) this;
        }

        public Criteria andSimpleNameNotBetween(String value1, String value2) {
            addCriterion("simple_name not between", value1, value2, "simpleName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameIsNull() {
            addCriterion("english_name is null");
            return (Criteria) this;
        }

        public Criteria andEnglishNameIsNotNull() {
            addCriterion("english_name is not null");
            return (Criteria) this;
        }

        public Criteria andEnglishNameEqualTo(String value) {
            addCriterion("english_name =", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotEqualTo(String value) {
            addCriterion("english_name <>", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameGreaterThan(String value) {
            addCriterion("english_name >", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameGreaterThanOrEqualTo(String value) {
            addCriterion("english_name >=", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameLessThan(String value) {
            addCriterion("english_name <", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameLessThanOrEqualTo(String value) {
            addCriterion("english_name <=", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameLike(String value) {
            addCriterion("english_name like", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotLike(String value) {
            addCriterion("english_name not like", value, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameIn(List<String> values) {
            addCriterion("english_name in", values, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotIn(List<String> values) {
            addCriterion("english_name not in", values, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameBetween(String value1, String value2) {
            addCriterion("english_name between", value1, value2, "englishName");
            return (Criteria) this;
        }

        public Criteria andEnglishNameNotBetween(String value1, String value2) {
            addCriterion("english_name not between", value1, value2, "englishName");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(Integer value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(Integer value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(Integer value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(Integer value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(Integer value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<Integer> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<Integer> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(Integer value1, Integer value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNull() {
            addCriterion("phone_no is null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIsNotNull() {
            addCriterion("phone_no is not null");
            return (Criteria) this;
        }

        public Criteria andPhoneNoEqualTo(String value) {
            addCriterion("phone_no =", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotEqualTo(String value) {
            addCriterion("phone_no <>", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThan(String value) {
            addCriterion("phone_no >", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoGreaterThanOrEqualTo(String value) {
            addCriterion("phone_no >=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThan(String value) {
            addCriterion("phone_no <", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLessThanOrEqualTo(String value) {
            addCriterion("phone_no <=", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoLike(String value) {
            addCriterion("phone_no like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotLike(String value) {
            addCriterion("phone_no not like", value, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoIn(List<String> values) {
            addCriterion("phone_no in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotIn(List<String> values) {
            addCriterion("phone_no not in", values, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoBetween(String value1, String value2) {
            addCriterion("phone_no between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andPhoneNoNotBetween(String value1, String value2) {
            addCriterion("phone_no not between", value1, value2, "phoneNo");
            return (Criteria) this;
        }

        public Criteria andLogoUrlIsNull() {
            addCriterion("logo_url is null");
            return (Criteria) this;
        }

        public Criteria andLogoUrlIsNotNull() {
            addCriterion("logo_url is not null");
            return (Criteria) this;
        }

        public Criteria andLogoUrlEqualTo(String value) {
            addCriterion("logo_url =", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotEqualTo(String value) {
            addCriterion("logo_url <>", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlGreaterThan(String value) {
            addCriterion("logo_url >", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlGreaterThanOrEqualTo(String value) {
            addCriterion("logo_url >=", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlLessThan(String value) {
            addCriterion("logo_url <", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlLessThanOrEqualTo(String value) {
            addCriterion("logo_url <=", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlLike(String value) {
            addCriterion("logo_url like", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotLike(String value) {
            addCriterion("logo_url not like", value, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlIn(List<String> values) {
            addCriterion("logo_url in", values, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotIn(List<String> values) {
            addCriterion("logo_url not in", values, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlBetween(String value1, String value2) {
            addCriterion("logo_url between", value1, value2, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andLogoUrlNotBetween(String value1, String value2) {
            addCriterion("logo_url not between", value1, value2, "logoUrl");
            return (Criteria) this;
        }

        public Criteria andSiteUrlIsNull() {
            addCriterion("site_url is null");
            return (Criteria) this;
        }

        public Criteria andSiteUrlIsNotNull() {
            addCriterion("site_url is not null");
            return (Criteria) this;
        }

        public Criteria andSiteUrlEqualTo(String value) {
            addCriterion("site_url =", value, "siteUrl");
            return (Criteria) this;
        }

        public Criteria andSiteUrlNotEqualTo(String value) {
            addCriterion("site_url <>", value, "siteUrl");
            return (Criteria) this;
        }

        public Criteria andSiteUrlGreaterThan(String value) {
            addCriterion("site_url >", value, "siteUrl");
            return (Criteria) this;
        }

        public Criteria andSiteUrlGreaterThanOrEqualTo(String value) {
            addCriterion("site_url >=", value, "siteUrl");
            return (Criteria) this;
        }

        public Criteria andSiteUrlLessThan(String value) {
            addCriterion("site_url <", value, "siteUrl");
            return (Criteria) this;
        }

        public Criteria andSiteUrlLessThanOrEqualTo(String value) {
            addCriterion("site_url <=", value, "siteUrl");
            return (Criteria) this;
        }

        public Criteria andSiteUrlLike(String value) {
            addCriterion("site_url like", value, "siteUrl");
            return (Criteria) this;
        }

        public Criteria andSiteUrlNotLike(String value) {
            addCriterion("site_url not like", value, "siteUrl");
            return (Criteria) this;
        }

        public Criteria andSiteUrlIn(List<String> values) {
            addCriterion("site_url in", values, "siteUrl");
            return (Criteria) this;
        }

        public Criteria andSiteUrlNotIn(List<String> values) {
            addCriterion("site_url not in", values, "siteUrl");
            return (Criteria) this;
        }

        public Criteria andSiteUrlBetween(String value1, String value2) {
            addCriterion("site_url between", value1, value2, "siteUrl");
            return (Criteria) this;
        }

        public Criteria andSiteUrlNotBetween(String value1, String value2) {
            addCriterion("site_url not between", value1, value2, "siteUrl");
            return (Criteria) this;
        }

        public Criteria andFinancingStatusIsNull() {
            addCriterion("financing_status is null");
            return (Criteria) this;
        }

        public Criteria andFinancingStatusIsNotNull() {
            addCriterion("financing_status is not null");
            return (Criteria) this;
        }

        public Criteria andFinancingStatusEqualTo(Integer value) {
            addCriterion("financing_status =", value, "financingStatus");
            return (Criteria) this;
        }

        public Criteria andFinancingStatusNotEqualTo(Integer value) {
            addCriterion("financing_status <>", value, "financingStatus");
            return (Criteria) this;
        }

        public Criteria andFinancingStatusGreaterThan(Integer value) {
            addCriterion("financing_status >", value, "financingStatus");
            return (Criteria) this;
        }

        public Criteria andFinancingStatusGreaterThanOrEqualTo(Integer value) {
            addCriterion("financing_status >=", value, "financingStatus");
            return (Criteria) this;
        }

        public Criteria andFinancingStatusLessThan(Integer value) {
            addCriterion("financing_status <", value, "financingStatus");
            return (Criteria) this;
        }

        public Criteria andFinancingStatusLessThanOrEqualTo(Integer value) {
            addCriterion("financing_status <=", value, "financingStatus");
            return (Criteria) this;
        }

        public Criteria andFinancingStatusIn(List<Integer> values) {
            addCriterion("financing_status in", values, "financingStatus");
            return (Criteria) this;
        }

        public Criteria andFinancingStatusNotIn(List<Integer> values) {
            addCriterion("financing_status not in", values, "financingStatus");
            return (Criteria) this;
        }

        public Criteria andFinancingStatusBetween(Integer value1, Integer value2) {
            addCriterion("financing_status between", value1, value2, "financingStatus");
            return (Criteria) this;
        }

        public Criteria andFinancingStatusNotBetween(Integer value1, Integer value2) {
            addCriterion("financing_status not between", value1, value2, "financingStatus");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountIsNull() {
            addCriterion("financing_amount is null");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountIsNotNull() {
            addCriterion("financing_amount is not null");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountEqualTo(BigDecimal value) {
            addCriterion("financing_amount =", value, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountNotEqualTo(BigDecimal value) {
            addCriterion("financing_amount <>", value, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountGreaterThan(BigDecimal value) {
            addCriterion("financing_amount >", value, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("financing_amount >=", value, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountLessThan(BigDecimal value) {
            addCriterion("financing_amount <", value, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountLessThanOrEqualTo(BigDecimal value) {
            addCriterion("financing_amount <=", value, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountIn(List<BigDecimal> values) {
            addCriterion("financing_amount in", values, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountNotIn(List<BigDecimal> values) {
            addCriterion("financing_amount not in", values, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("financing_amount between", value1, value2, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andFinancingAmountNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("financing_amount not between", value1, value2, "financingAmount");
            return (Criteria) this;
        }

        public Criteria andLegalPersonIsNull() {
            addCriterion("legal_person is null");
            return (Criteria) this;
        }

        public Criteria andLegalPersonIsNotNull() {
            addCriterion("legal_person is not null");
            return (Criteria) this;
        }

        public Criteria andLegalPersonEqualTo(String value) {
            addCriterion("legal_person =", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotEqualTo(String value) {
            addCriterion("legal_person <>", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonGreaterThan(String value) {
            addCriterion("legal_person >", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonGreaterThanOrEqualTo(String value) {
            addCriterion("legal_person >=", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonLessThan(String value) {
            addCriterion("legal_person <", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonLessThanOrEqualTo(String value) {
            addCriterion("legal_person <=", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonLike(String value) {
            addCriterion("legal_person like", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotLike(String value) {
            addCriterion("legal_person not like", value, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonIn(List<String> values) {
            addCriterion("legal_person in", values, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotIn(List<String> values) {
            addCriterion("legal_person not in", values, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonBetween(String value1, String value2) {
            addCriterion("legal_person between", value1, value2, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andLegalPersonNotBetween(String value1, String value2) {
            addCriterion("legal_person not between", value1, value2, "legalPerson");
            return (Criteria) this;
        }

        public Criteria andRegistedCapitalIsNull() {
            addCriterion("registed_capital is null");
            return (Criteria) this;
        }

        public Criteria andRegistedCapitalIsNotNull() {
            addCriterion("registed_capital is not null");
            return (Criteria) this;
        }

        public Criteria andRegistedCapitalEqualTo(BigDecimal value) {
            addCriterion("registed_capital =", value, "registedCapital");
            return (Criteria) this;
        }

        public Criteria andRegistedCapitalNotEqualTo(BigDecimal value) {
            addCriterion("registed_capital <>", value, "registedCapital");
            return (Criteria) this;
        }

        public Criteria andRegistedCapitalGreaterThan(BigDecimal value) {
            addCriterion("registed_capital >", value, "registedCapital");
            return (Criteria) this;
        }

        public Criteria andRegistedCapitalGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("registed_capital >=", value, "registedCapital");
            return (Criteria) this;
        }

        public Criteria andRegistedCapitalLessThan(BigDecimal value) {
            addCriterion("registed_capital <", value, "registedCapital");
            return (Criteria) this;
        }

        public Criteria andRegistedCapitalLessThanOrEqualTo(BigDecimal value) {
            addCriterion("registed_capital <=", value, "registedCapital");
            return (Criteria) this;
        }

        public Criteria andRegistedCapitalIn(List<BigDecimal> values) {
            addCriterion("registed_capital in", values, "registedCapital");
            return (Criteria) this;
        }

        public Criteria andRegistedCapitalNotIn(List<BigDecimal> values) {
            addCriterion("registed_capital not in", values, "registedCapital");
            return (Criteria) this;
        }

        public Criteria andRegistedCapitalBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("registed_capital between", value1, value2, "registedCapital");
            return (Criteria) this;
        }

        public Criteria andRegistedCapitalNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("registed_capital not between", value1, value2, "registedCapital");
            return (Criteria) this;
        }

        public Criteria andRegistedAtIsNull() {
            addCriterion("registed_at is null");
            return (Criteria) this;
        }

        public Criteria andRegistedAtIsNotNull() {
            addCriterion("registed_at is not null");
            return (Criteria) this;
        }

        public Criteria andRegistedAtEqualTo(Date value) {
            addCriterion("registed_at =", value, "registedAt");
            return (Criteria) this;
        }

        public Criteria andRegistedAtNotEqualTo(Date value) {
            addCriterion("registed_at <>", value, "registedAt");
            return (Criteria) this;
        }

        public Criteria andRegistedAtGreaterThan(Date value) {
            addCriterion("registed_at >", value, "registedAt");
            return (Criteria) this;
        }

        public Criteria andRegistedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("registed_at >=", value, "registedAt");
            return (Criteria) this;
        }

        public Criteria andRegistedAtLessThan(Date value) {
            addCriterion("registed_at <", value, "registedAt");
            return (Criteria) this;
        }

        public Criteria andRegistedAtLessThanOrEqualTo(Date value) {
            addCriterion("registed_at <=", value, "registedAt");
            return (Criteria) this;
        }

        public Criteria andRegistedAtIn(List<Date> values) {
            addCriterion("registed_at in", values, "registedAt");
            return (Criteria) this;
        }

        public Criteria andRegistedAtNotIn(List<Date> values) {
            addCriterion("registed_at not in", values, "registedAt");
            return (Criteria) this;
        }

        public Criteria andRegistedAtBetween(Date value1, Date value2) {
            addCriterion("registed_at between", value1, value2, "registedAt");
            return (Criteria) this;
        }

        public Criteria andRegistedAtNotBetween(Date value1, Date value2) {
            addCriterion("registed_at not between", value1, value2, "registedAt");
            return (Criteria) this;
        }

        public Criteria andTurnoverIsNull() {
            addCriterion("turnover is null");
            return (Criteria) this;
        }

        public Criteria andTurnoverIsNotNull() {
            addCriterion("turnover is not null");
            return (Criteria) this;
        }

        public Criteria andTurnoverEqualTo(BigDecimal value) {
            addCriterion("turnover =", value, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverNotEqualTo(BigDecimal value) {
            addCriterion("turnover <>", value, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverGreaterThan(BigDecimal value) {
            addCriterion("turnover >", value, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("turnover >=", value, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverLessThan(BigDecimal value) {
            addCriterion("turnover <", value, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverLessThanOrEqualTo(BigDecimal value) {
            addCriterion("turnover <=", value, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverIn(List<BigDecimal> values) {
            addCriterion("turnover in", values, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverNotIn(List<BigDecimal> values) {
            addCriterion("turnover not in", values, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("turnover between", value1, value2, "turnover");
            return (Criteria) this;
        }

        public Criteria andTurnoverNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("turnover not between", value1, value2, "turnover");
            return (Criteria) this;
        }

        public Criteria andRegistedNoIsNull() {
            addCriterion("registed_no is null");
            return (Criteria) this;
        }

        public Criteria andRegistedNoIsNotNull() {
            addCriterion("registed_no is not null");
            return (Criteria) this;
        }

        public Criteria andRegistedNoEqualTo(String value) {
            addCriterion("registed_no =", value, "registedNo");
            return (Criteria) this;
        }

        public Criteria andRegistedNoNotEqualTo(String value) {
            addCriterion("registed_no <>", value, "registedNo");
            return (Criteria) this;
        }

        public Criteria andRegistedNoGreaterThan(String value) {
            addCriterion("registed_no >", value, "registedNo");
            return (Criteria) this;
        }

        public Criteria andRegistedNoGreaterThanOrEqualTo(String value) {
            addCriterion("registed_no >=", value, "registedNo");
            return (Criteria) this;
        }

        public Criteria andRegistedNoLessThan(String value) {
            addCriterion("registed_no <", value, "registedNo");
            return (Criteria) this;
        }

        public Criteria andRegistedNoLessThanOrEqualTo(String value) {
            addCriterion("registed_no <=", value, "registedNo");
            return (Criteria) this;
        }

        public Criteria andRegistedNoLike(String value) {
            addCriterion("registed_no like", value, "registedNo");
            return (Criteria) this;
        }

        public Criteria andRegistedNoNotLike(String value) {
            addCriterion("registed_no not like", value, "registedNo");
            return (Criteria) this;
        }

        public Criteria andRegistedNoIn(List<String> values) {
            addCriterion("registed_no in", values, "registedNo");
            return (Criteria) this;
        }

        public Criteria andRegistedNoNotIn(List<String> values) {
            addCriterion("registed_no not in", values, "registedNo");
            return (Criteria) this;
        }

        public Criteria andRegistedNoBetween(String value1, String value2) {
            addCriterion("registed_no between", value1, value2, "registedNo");
            return (Criteria) this;
        }

        public Criteria andRegistedNoNotBetween(String value1, String value2) {
            addCriterion("registed_no not between", value1, value2, "registedNo");
            return (Criteria) this;
        }

        public Criteria andRegistedAuthorityIsNull() {
            addCriterion("registed_authority is null");
            return (Criteria) this;
        }

        public Criteria andRegistedAuthorityIsNotNull() {
            addCriterion("registed_authority is not null");
            return (Criteria) this;
        }

        public Criteria andRegistedAuthorityEqualTo(String value) {
            addCriterion("registed_authority =", value, "registedAuthority");
            return (Criteria) this;
        }

        public Criteria andRegistedAuthorityNotEqualTo(String value) {
            addCriterion("registed_authority <>", value, "registedAuthority");
            return (Criteria) this;
        }

        public Criteria andRegistedAuthorityGreaterThan(String value) {
            addCriterion("registed_authority >", value, "registedAuthority");
            return (Criteria) this;
        }

        public Criteria andRegistedAuthorityGreaterThanOrEqualTo(String value) {
            addCriterion("registed_authority >=", value, "registedAuthority");
            return (Criteria) this;
        }

        public Criteria andRegistedAuthorityLessThan(String value) {
            addCriterion("registed_authority <", value, "registedAuthority");
            return (Criteria) this;
        }

        public Criteria andRegistedAuthorityLessThanOrEqualTo(String value) {
            addCriterion("registed_authority <=", value, "registedAuthority");
            return (Criteria) this;
        }

        public Criteria andRegistedAuthorityLike(String value) {
            addCriterion("registed_authority like", value, "registedAuthority");
            return (Criteria) this;
        }

        public Criteria andRegistedAuthorityNotLike(String value) {
            addCriterion("registed_authority not like", value, "registedAuthority");
            return (Criteria) this;
        }

        public Criteria andRegistedAuthorityIn(List<String> values) {
            addCriterion("registed_authority in", values, "registedAuthority");
            return (Criteria) this;
        }

        public Criteria andRegistedAuthorityNotIn(List<String> values) {
            addCriterion("registed_authority not in", values, "registedAuthority");
            return (Criteria) this;
        }

        public Criteria andRegistedAuthorityBetween(String value1, String value2) {
            addCriterion("registed_authority between", value1, value2, "registedAuthority");
            return (Criteria) this;
        }

        public Criteria andRegistedAuthorityNotBetween(String value1, String value2) {
            addCriterion("registed_authority not between", value1, value2, "registedAuthority");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNull() {
            addCriterion("parent_id is null");
            return (Criteria) this;
        }

        public Criteria andParentIdIsNotNull() {
            addCriterion("parent_id is not null");
            return (Criteria) this;
        }

        public Criteria andParentIdEqualTo(Long value) {
            addCriterion("parent_id =", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotEqualTo(Long value) {
            addCriterion("parent_id <>", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThan(Long value) {
            addCriterion("parent_id >", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdGreaterThanOrEqualTo(Long value) {
            addCriterion("parent_id >=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThan(Long value) {
            addCriterion("parent_id <", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdLessThanOrEqualTo(Long value) {
            addCriterion("parent_id <=", value, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdIn(List<Long> values) {
            addCriterion("parent_id in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotIn(List<Long> values) {
            addCriterion("parent_id not in", values, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdBetween(Long value1, Long value2) {
            addCriterion("parent_id between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andParentIdNotBetween(Long value1, Long value2) {
            addCriterion("parent_id not between", value1, value2, "parentId");
            return (Criteria) this;
        }

        public Criteria andNatureCodeIsNull() {
            addCriterion("nature_code is null");
            return (Criteria) this;
        }

        public Criteria andNatureCodeIsNotNull() {
            addCriterion("nature_code is not null");
            return (Criteria) this;
        }

        public Criteria andNatureCodeEqualTo(Integer value) {
            addCriterion("nature_code =", value, "natureCode");
            return (Criteria) this;
        }

        public Criteria andNatureCodeNotEqualTo(Integer value) {
            addCriterion("nature_code <>", value, "natureCode");
            return (Criteria) this;
        }

        public Criteria andNatureCodeGreaterThan(Integer value) {
            addCriterion("nature_code >", value, "natureCode");
            return (Criteria) this;
        }

        public Criteria andNatureCodeGreaterThanOrEqualTo(Integer value) {
            addCriterion("nature_code >=", value, "natureCode");
            return (Criteria) this;
        }

        public Criteria andNatureCodeLessThan(Integer value) {
            addCriterion("nature_code <", value, "natureCode");
            return (Criteria) this;
        }

        public Criteria andNatureCodeLessThanOrEqualTo(Integer value) {
            addCriterion("nature_code <=", value, "natureCode");
            return (Criteria) this;
        }

        public Criteria andNatureCodeIn(List<Integer> values) {
            addCriterion("nature_code in", values, "natureCode");
            return (Criteria) this;
        }

        public Criteria andNatureCodeNotIn(List<Integer> values) {
            addCriterion("nature_code not in", values, "natureCode");
            return (Criteria) this;
        }

        public Criteria andNatureCodeBetween(Integer value1, Integer value2) {
            addCriterion("nature_code between", value1, value2, "natureCode");
            return (Criteria) this;
        }

        public Criteria andNatureCodeNotBetween(Integer value1, Integer value2) {
            addCriterion("nature_code not between", value1, value2, "natureCode");
            return (Criteria) this;
        }

        public Criteria andEmpScaleIsNull() {
            addCriterion("emp_scale is null");
            return (Criteria) this;
        }

        public Criteria andEmpScaleIsNotNull() {
            addCriterion("emp_scale is not null");
            return (Criteria) this;
        }

        public Criteria andEmpScaleEqualTo(Integer value) {
            addCriterion("emp_scale =", value, "empScale");
            return (Criteria) this;
        }

        public Criteria andEmpScaleNotEqualTo(Integer value) {
            addCriterion("emp_scale <>", value, "empScale");
            return (Criteria) this;
        }

        public Criteria andEmpScaleGreaterThan(Integer value) {
            addCriterion("emp_scale >", value, "empScale");
            return (Criteria) this;
        }

        public Criteria andEmpScaleGreaterThanOrEqualTo(Integer value) {
            addCriterion("emp_scale >=", value, "empScale");
            return (Criteria) this;
        }

        public Criteria andEmpScaleLessThan(Integer value) {
            addCriterion("emp_scale <", value, "empScale");
            return (Criteria) this;
        }

        public Criteria andEmpScaleLessThanOrEqualTo(Integer value) {
            addCriterion("emp_scale <=", value, "empScale");
            return (Criteria) this;
        }

        public Criteria andEmpScaleIn(List<Integer> values) {
            addCriterion("emp_scale in", values, "empScale");
            return (Criteria) this;
        }

        public Criteria andEmpScaleNotIn(List<Integer> values) {
            addCriterion("emp_scale not in", values, "empScale");
            return (Criteria) this;
        }

        public Criteria andEmpScaleBetween(Integer value1, Integer value2) {
            addCriterion("emp_scale between", value1, value2, "empScale");
            return (Criteria) this;
        }

        public Criteria andEmpScaleNotBetween(Integer value1, Integer value2) {
            addCriterion("emp_scale not between", value1, value2, "empScale");
            return (Criteria) this;
        }

        public Criteria andEmpMeanSalaryIsNull() {
            addCriterion("emp_mean_salary is null");
            return (Criteria) this;
        }

        public Criteria andEmpMeanSalaryIsNotNull() {
            addCriterion("emp_mean_salary is not null");
            return (Criteria) this;
        }

        public Criteria andEmpMeanSalaryEqualTo(Integer value) {
            addCriterion("emp_mean_salary =", value, "empMeanSalary");
            return (Criteria) this;
        }

        public Criteria andEmpMeanSalaryNotEqualTo(Integer value) {
            addCriterion("emp_mean_salary <>", value, "empMeanSalary");
            return (Criteria) this;
        }

        public Criteria andEmpMeanSalaryGreaterThan(Integer value) {
            addCriterion("emp_mean_salary >", value, "empMeanSalary");
            return (Criteria) this;
        }

        public Criteria andEmpMeanSalaryGreaterThanOrEqualTo(Integer value) {
            addCriterion("emp_mean_salary >=", value, "empMeanSalary");
            return (Criteria) this;
        }

        public Criteria andEmpMeanSalaryLessThan(Integer value) {
            addCriterion("emp_mean_salary <", value, "empMeanSalary");
            return (Criteria) this;
        }

        public Criteria andEmpMeanSalaryLessThanOrEqualTo(Integer value) {
            addCriterion("emp_mean_salary <=", value, "empMeanSalary");
            return (Criteria) this;
        }

        public Criteria andEmpMeanSalaryIn(List<Integer> values) {
            addCriterion("emp_mean_salary in", values, "empMeanSalary");
            return (Criteria) this;
        }

        public Criteria andEmpMeanSalaryNotIn(List<Integer> values) {
            addCriterion("emp_mean_salary not in", values, "empMeanSalary");
            return (Criteria) this;
        }

        public Criteria andEmpMeanSalaryBetween(Integer value1, Integer value2) {
            addCriterion("emp_mean_salary between", value1, value2, "empMeanSalary");
            return (Criteria) this;
        }

        public Criteria andEmpMeanSalaryNotBetween(Integer value1, Integer value2) {
            addCriterion("emp_mean_salary not between", value1, value2, "empMeanSalary");
            return (Criteria) this;
        }

        public Criteria andWxPublicNoIsNull() {
            addCriterion("wx_public_no is null");
            return (Criteria) this;
        }

        public Criteria andWxPublicNoIsNotNull() {
            addCriterion("wx_public_no is not null");
            return (Criteria) this;
        }

        public Criteria andWxPublicNoEqualTo(String value) {
            addCriterion("wx_public_no =", value, "wxPublicNo");
            return (Criteria) this;
        }

        public Criteria andWxPublicNoNotEqualTo(String value) {
            addCriterion("wx_public_no <>", value, "wxPublicNo");
            return (Criteria) this;
        }

        public Criteria andWxPublicNoGreaterThan(String value) {
            addCriterion("wx_public_no >", value, "wxPublicNo");
            return (Criteria) this;
        }

        public Criteria andWxPublicNoGreaterThanOrEqualTo(String value) {
            addCriterion("wx_public_no >=", value, "wxPublicNo");
            return (Criteria) this;
        }

        public Criteria andWxPublicNoLessThan(String value) {
            addCriterion("wx_public_no <", value, "wxPublicNo");
            return (Criteria) this;
        }

        public Criteria andWxPublicNoLessThanOrEqualTo(String value) {
            addCriterion("wx_public_no <=", value, "wxPublicNo");
            return (Criteria) this;
        }

        public Criteria andWxPublicNoLike(String value) {
            addCriterion("wx_public_no like", value, "wxPublicNo");
            return (Criteria) this;
        }

        public Criteria andWxPublicNoNotLike(String value) {
            addCriterion("wx_public_no not like", value, "wxPublicNo");
            return (Criteria) this;
        }

        public Criteria andWxPublicNoIn(List<String> values) {
            addCriterion("wx_public_no in", values, "wxPublicNo");
            return (Criteria) this;
        }

        public Criteria andWxPublicNoNotIn(List<String> values) {
            addCriterion("wx_public_no not in", values, "wxPublicNo");
            return (Criteria) this;
        }

        public Criteria andWxPublicNoBetween(String value1, String value2) {
            addCriterion("wx_public_no between", value1, value2, "wxPublicNo");
            return (Criteria) this;
        }

        public Criteria andWxPublicNoNotBetween(String value1, String value2) {
            addCriterion("wx_public_no not between", value1, value2, "wxPublicNo");
            return (Criteria) this;
        }

        public Criteria andLinkedinUrlIsNull() {
            addCriterion("linkedin_url is null");
            return (Criteria) this;
        }

        public Criteria andLinkedinUrlIsNotNull() {
            addCriterion("linkedin_url is not null");
            return (Criteria) this;
        }

        public Criteria andLinkedinUrlEqualTo(String value) {
            addCriterion("linkedin_url =", value, "linkedinUrl");
            return (Criteria) this;
        }

        public Criteria andLinkedinUrlNotEqualTo(String value) {
            addCriterion("linkedin_url <>", value, "linkedinUrl");
            return (Criteria) this;
        }

        public Criteria andLinkedinUrlGreaterThan(String value) {
            addCriterion("linkedin_url >", value, "linkedinUrl");
            return (Criteria) this;
        }

        public Criteria andLinkedinUrlGreaterThanOrEqualTo(String value) {
            addCriterion("linkedin_url >=", value, "linkedinUrl");
            return (Criteria) this;
        }

        public Criteria andLinkedinUrlLessThan(String value) {
            addCriterion("linkedin_url <", value, "linkedinUrl");
            return (Criteria) this;
        }

        public Criteria andLinkedinUrlLessThanOrEqualTo(String value) {
            addCriterion("linkedin_url <=", value, "linkedinUrl");
            return (Criteria) this;
        }

        public Criteria andLinkedinUrlLike(String value) {
            addCriterion("linkedin_url like", value, "linkedinUrl");
            return (Criteria) this;
        }

        public Criteria andLinkedinUrlNotLike(String value) {
            addCriterion("linkedin_url not like", value, "linkedinUrl");
            return (Criteria) this;
        }

        public Criteria andLinkedinUrlIn(List<String> values) {
            addCriterion("linkedin_url in", values, "linkedinUrl");
            return (Criteria) this;
        }

        public Criteria andLinkedinUrlNotIn(List<String> values) {
            addCriterion("linkedin_url not in", values, "linkedinUrl");
            return (Criteria) this;
        }

        public Criteria andLinkedinUrlBetween(String value1, String value2) {
            addCriterion("linkedin_url between", value1, value2, "linkedinUrl");
            return (Criteria) this;
        }

        public Criteria andLinkedinUrlNotBetween(String value1, String value2) {
            addCriterion("linkedin_url not between", value1, value2, "linkedinUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlIsNull() {
            addCriterion("weibo_url is null");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlIsNotNull() {
            addCriterion("weibo_url is not null");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlEqualTo(String value) {
            addCriterion("weibo_url =", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlNotEqualTo(String value) {
            addCriterion("weibo_url <>", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlGreaterThan(String value) {
            addCriterion("weibo_url >", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlGreaterThanOrEqualTo(String value) {
            addCriterion("weibo_url >=", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlLessThan(String value) {
            addCriterion("weibo_url <", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlLessThanOrEqualTo(String value) {
            addCriterion("weibo_url <=", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlLike(String value) {
            addCriterion("weibo_url like", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlNotLike(String value) {
            addCriterion("weibo_url not like", value, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlIn(List<String> values) {
            addCriterion("weibo_url in", values, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlNotIn(List<String> values) {
            addCriterion("weibo_url not in", values, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlBetween(String value1, String value2) {
            addCriterion("weibo_url between", value1, value2, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andWeiboUrlNotBetween(String value1, String value2) {
            addCriterion("weibo_url not between", value1, value2, "weiboUrl");
            return (Criteria) this;
        }

        public Criteria andSourceIsNull() {
            addCriterion("source is null");
            return (Criteria) this;
        }

        public Criteria andSourceIsNotNull() {
            addCriterion("source is not null");
            return (Criteria) this;
        }

        public Criteria andSourceEqualTo(Integer value) {
            addCriterion("source =", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotEqualTo(Integer value) {
            addCriterion("source <>", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThan(Integer value) {
            addCriterion("source >", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceGreaterThanOrEqualTo(Integer value) {
            addCriterion("source >=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThan(Integer value) {
            addCriterion("source <", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceLessThanOrEqualTo(Integer value) {
            addCriterion("source <=", value, "source");
            return (Criteria) this;
        }

        public Criteria andSourceIn(List<Integer> values) {
            addCriterion("source in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotIn(List<Integer> values) {
            addCriterion("source not in", values, "source");
            return (Criteria) this;
        }

        public Criteria andSourceBetween(Integer value1, Integer value2) {
            addCriterion("source between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andSourceNotBetween(Integer value1, Integer value2) {
            addCriterion("source not between", value1, value2, "source");
            return (Criteria) this;
        }

        public Criteria andQccUniqueIsNull() {
            addCriterion("qcc_unique is null");
            return (Criteria) this;
        }

        public Criteria andQccUniqueIsNotNull() {
            addCriterion("qcc_unique is not null");
            return (Criteria) this;
        }

        public Criteria andQccUniqueEqualTo(String value) {
            addCriterion("qcc_unique =", value, "qccUnique");
            return (Criteria) this;
        }

        public Criteria andQccUniqueNotEqualTo(String value) {
            addCriterion("qcc_unique <>", value, "qccUnique");
            return (Criteria) this;
        }

        public Criteria andQccUniqueGreaterThan(String value) {
            addCriterion("qcc_unique >", value, "qccUnique");
            return (Criteria) this;
        }

        public Criteria andQccUniqueGreaterThanOrEqualTo(String value) {
            addCriterion("qcc_unique >=", value, "qccUnique");
            return (Criteria) this;
        }

        public Criteria andQccUniqueLessThan(String value) {
            addCriterion("qcc_unique <", value, "qccUnique");
            return (Criteria) this;
        }

        public Criteria andQccUniqueLessThanOrEqualTo(String value) {
            addCriterion("qcc_unique <=", value, "qccUnique");
            return (Criteria) this;
        }

        public Criteria andQccUniqueLike(String value) {
            addCriterion("qcc_unique like", value, "qccUnique");
            return (Criteria) this;
        }

        public Criteria andQccUniqueNotLike(String value) {
            addCriterion("qcc_unique not like", value, "qccUnique");
            return (Criteria) this;
        }

        public Criteria andQccUniqueIn(List<String> values) {
            addCriterion("qcc_unique in", values, "qccUnique");
            return (Criteria) this;
        }

        public Criteria andQccUniqueNotIn(List<String> values) {
            addCriterion("qcc_unique not in", values, "qccUnique");
            return (Criteria) this;
        }

        public Criteria andQccUniqueBetween(String value1, String value2) {
            addCriterion("qcc_unique between", value1, value2, "qccUnique");
            return (Criteria) this;
        }

        public Criteria andQccUniqueNotBetween(String value1, String value2) {
            addCriterion("qcc_unique not between", value1, value2, "qccUnique");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNull() {
            addCriterion("org_code is null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIsNotNull() {
            addCriterion("org_code is not null");
            return (Criteria) this;
        }

        public Criteria andOrgCodeEqualTo(String value) {
            addCriterion("org_code =", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotEqualTo(String value) {
            addCriterion("org_code <>", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThan(String value) {
            addCriterion("org_code >", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeGreaterThanOrEqualTo(String value) {
            addCriterion("org_code >=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThan(String value) {
            addCriterion("org_code <", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLessThanOrEqualTo(String value) {
            addCriterion("org_code <=", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeLike(String value) {
            addCriterion("org_code like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotLike(String value) {
            addCriterion("org_code not like", value, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeIn(List<String> values) {
            addCriterion("org_code in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotIn(List<String> values) {
            addCriterion("org_code not in", values, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeBetween(String value1, String value2) {
            addCriterion("org_code between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andOrgCodeNotBetween(String value1, String value2) {
            addCriterion("org_code not between", value1, value2, "orgCode");
            return (Criteria) this;
        }

        public Criteria andLicenseNoIsNull() {
            addCriterion("license_no is null");
            return (Criteria) this;
        }

        public Criteria andLicenseNoIsNotNull() {
            addCriterion("license_no is not null");
            return (Criteria) this;
        }

        public Criteria andLicenseNoEqualTo(String value) {
            addCriterion("license_no =", value, "licenseNo");
            return (Criteria) this;
        }

        public Criteria andLicenseNoNotEqualTo(String value) {
            addCriterion("license_no <>", value, "licenseNo");
            return (Criteria) this;
        }

        public Criteria andLicenseNoGreaterThan(String value) {
            addCriterion("license_no >", value, "licenseNo");
            return (Criteria) this;
        }

        public Criteria andLicenseNoGreaterThanOrEqualTo(String value) {
            addCriterion("license_no >=", value, "licenseNo");
            return (Criteria) this;
        }

        public Criteria andLicenseNoLessThan(String value) {
            addCriterion("license_no <", value, "licenseNo");
            return (Criteria) this;
        }

        public Criteria andLicenseNoLessThanOrEqualTo(String value) {
            addCriterion("license_no <=", value, "licenseNo");
            return (Criteria) this;
        }

        public Criteria andLicenseNoLike(String value) {
            addCriterion("license_no like", value, "licenseNo");
            return (Criteria) this;
        }

        public Criteria andLicenseNoNotLike(String value) {
            addCriterion("license_no not like", value, "licenseNo");
            return (Criteria) this;
        }

        public Criteria andLicenseNoIn(List<String> values) {
            addCriterion("license_no in", values, "licenseNo");
            return (Criteria) this;
        }

        public Criteria andLicenseNoNotIn(List<String> values) {
            addCriterion("license_no not in", values, "licenseNo");
            return (Criteria) this;
        }

        public Criteria andLicenseNoBetween(String value1, String value2) {
            addCriterion("license_no between", value1, value2, "licenseNo");
            return (Criteria) this;
        }

        public Criteria andLicenseNoNotBetween(String value1, String value2) {
            addCriterion("license_no not between", value1, value2, "licenseNo");
            return (Criteria) this;
        }

        public Criteria andReasonTypeIsNull() {
            addCriterion("reason_type is null");
            return (Criteria) this;
        }

        public Criteria andReasonTypeIsNotNull() {
            addCriterion("reason_type is not null");
            return (Criteria) this;
        }

        public Criteria andReasonTypeEqualTo(Integer value) {
            addCriterion("reason_type =", value, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeNotEqualTo(Integer value) {
            addCriterion("reason_type <>", value, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeGreaterThan(Integer value) {
            addCriterion("reason_type >", value, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeGreaterThanOrEqualTo(Integer value) {
            addCriterion("reason_type >=", value, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeLessThan(Integer value) {
            addCriterion("reason_type <", value, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeLessThanOrEqualTo(Integer value) {
            addCriterion("reason_type <=", value, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeIn(List<Integer> values) {
            addCriterion("reason_type in", values, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeNotIn(List<Integer> values) {
            addCriterion("reason_type not in", values, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeBetween(Integer value1, Integer value2) {
            addCriterion("reason_type between", value1, value2, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonTypeNotBetween(Integer value1, Integer value2) {
            addCriterion("reason_type not between", value1, value2, "reasonType");
            return (Criteria) this;
        }

        public Criteria andReasonIsNull() {
            addCriterion("reason is null");
            return (Criteria) this;
        }

        public Criteria andReasonIsNotNull() {
            addCriterion("reason is not null");
            return (Criteria) this;
        }

        public Criteria andReasonEqualTo(String value) {
            addCriterion("reason =", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotEqualTo(String value) {
            addCriterion("reason <>", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThan(String value) {
            addCriterion("reason >", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonGreaterThanOrEqualTo(String value) {
            addCriterion("reason >=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThan(String value) {
            addCriterion("reason <", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLessThanOrEqualTo(String value) {
            addCriterion("reason <=", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonLike(String value) {
            addCriterion("reason like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotLike(String value) {
            addCriterion("reason not like", value, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonIn(List<String> values) {
            addCriterion("reason in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotIn(List<String> values) {
            addCriterion("reason not in", values, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonBetween(String value1, String value2) {
            addCriterion("reason between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andReasonNotBetween(String value1, String value2) {
            addCriterion("reason not between", value1, value2, "reason");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNull() {
            addCriterion("owner_id is null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIsNotNull() {
            addCriterion("owner_id is not null");
            return (Criteria) this;
        }

        public Criteria andOwnerIdEqualTo(Long value) {
            addCriterion("owner_id =", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotEqualTo(Long value) {
            addCriterion("owner_id <>", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThan(Long value) {
            addCriterion("owner_id >", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdGreaterThanOrEqualTo(Long value) {
            addCriterion("owner_id >=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThan(Long value) {
            addCriterion("owner_id <", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdLessThanOrEqualTo(Long value) {
            addCriterion("owner_id <=", value, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdIn(List<Long> values) {
            addCriterion("owner_id in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotIn(List<Long> values) {
            addCriterion("owner_id not in", values, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdBetween(Long value1, Long value2) {
            addCriterion("owner_id between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andOwnerIdNotBetween(Long value1, Long value2) {
            addCriterion("owner_id not between", value1, value2, "ownerId");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNull() {
            addCriterion("created_by is null");
            return (Criteria) this;
        }

        public Criteria andCreatedByIsNotNull() {
            addCriterion("created_by is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedByEqualTo(Long value) {
            addCriterion("created_by =", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotEqualTo(Long value) {
            addCriterion("created_by <>", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThan(Long value) {
            addCriterion("created_by >", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByGreaterThanOrEqualTo(Long value) {
            addCriterion("created_by >=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThan(Long value) {
            addCriterion("created_by <", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByLessThanOrEqualTo(Long value) {
            addCriterion("created_by <=", value, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByIn(List<Long> values) {
            addCriterion("created_by in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotIn(List<Long> values) {
            addCriterion("created_by not in", values, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByBetween(Long value1, Long value2) {
            addCriterion("created_by between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andCreatedByNotBetween(Long value1, Long value2) {
            addCriterion("created_by not between", value1, value2, "createdBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNull() {
            addCriterion("updated_by is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIsNotNull() {
            addCriterion("updated_by is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedByEqualTo(Long value) {
            addCriterion("updated_by =", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotEqualTo(Long value) {
            addCriterion("updated_by <>", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThan(Long value) {
            addCriterion("updated_by >", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByGreaterThanOrEqualTo(Long value) {
            addCriterion("updated_by >=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThan(Long value) {
            addCriterion("updated_by <", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByLessThanOrEqualTo(Long value) {
            addCriterion("updated_by <=", value, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByIn(List<Long> values) {
            addCriterion("updated_by in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotIn(List<Long> values) {
            addCriterion("updated_by not in", values, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByBetween(Long value1, Long value2) {
            addCriterion("updated_by between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andUpdatedByNotBetween(Long value1, Long value2) {
            addCriterion("updated_by not between", value1, value2, "updatedBy");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNull() {
            addCriterion("created_at is null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIsNotNull() {
            addCriterion("created_at is not null");
            return (Criteria) this;
        }

        public Criteria andCreatedAtEqualTo(Date value) {
            addCriterion("created_at =", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotEqualTo(Date value) {
            addCriterion("created_at <>", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThan(Date value) {
            addCriterion("created_at >", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("created_at >=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThan(Date value) {
            addCriterion("created_at <", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtLessThanOrEqualTo(Date value) {
            addCriterion("created_at <=", value, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtIn(List<Date> values) {
            addCriterion("created_at in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotIn(List<Date> values) {
            addCriterion("created_at not in", values, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtBetween(Date value1, Date value2) {
            addCriterion("created_at between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andCreatedAtNotBetween(Date value1, Date value2) {
            addCriterion("created_at not between", value1, value2, "createdAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNull() {
            addCriterion("updated_at is null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIsNotNull() {
            addCriterion("updated_at is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtEqualTo(Date value) {
            addCriterion("updated_at =", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotEqualTo(Date value) {
            addCriterion("updated_at <>", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThan(Date value) {
            addCriterion("updated_at >", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtGreaterThanOrEqualTo(Date value) {
            addCriterion("updated_at >=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThan(Date value) {
            addCriterion("updated_at <", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtLessThanOrEqualTo(Date value) {
            addCriterion("updated_at <=", value, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtIn(List<Date> values) {
            addCriterion("updated_at in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotIn(List<Date> values) {
            addCriterion("updated_at not in", values, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtBetween(Date value1, Date value2) {
            addCriterion("updated_at between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andUpdatedAtNotBetween(Date value1, Date value2) {
            addCriterion("updated_at not between", value1, value2, "updatedAt");
            return (Criteria) this;
        }

        public Criteria andLatestEventAtIsNull() {
            addCriterion("latest_event_at is null");
            return (Criteria) this;
        }

        public Criteria andLatestEventAtIsNotNull() {
            addCriterion("latest_event_at is not null");
            return (Criteria) this;
        }

        public Criteria andLatestEventAtEqualTo(Date value) {
            addCriterion("latest_event_at =", value, "latestEventAt");
            return (Criteria) this;
        }

        public Criteria andLatestEventAtNotEqualTo(Date value) {
            addCriterion("latest_event_at <>", value, "latestEventAt");
            return (Criteria) this;
        }

        public Criteria andLatestEventAtGreaterThan(Date value) {
            addCriterion("latest_event_at >", value, "latestEventAt");
            return (Criteria) this;
        }

        public Criteria andLatestEventAtGreaterThanOrEqualTo(Date value) {
            addCriterion("latest_event_at >=", value, "latestEventAt");
            return (Criteria) this;
        }

        public Criteria andLatestEventAtLessThan(Date value) {
            addCriterion("latest_event_at <", value, "latestEventAt");
            return (Criteria) this;
        }

        public Criteria andLatestEventAtLessThanOrEqualTo(Date value) {
            addCriterion("latest_event_at <=", value, "latestEventAt");
            return (Criteria) this;
        }

        public Criteria andLatestEventAtIn(List<Date> values) {
            addCriterion("latest_event_at in", values, "latestEventAt");
            return (Criteria) this;
        }

        public Criteria andLatestEventAtNotIn(List<Date> values) {
            addCriterion("latest_event_at not in", values, "latestEventAt");
            return (Criteria) this;
        }

        public Criteria andLatestEventAtBetween(Date value1, Date value2) {
            addCriterion("latest_event_at between", value1, value2, "latestEventAt");
            return (Criteria) this;
        }

        public Criteria andLatestEventAtNotBetween(Date value1, Date value2) {
            addCriterion("latest_event_at not between", value1, value2, "latestEventAt");
            return (Criteria) this;
        }

        public Criteria andLatestIndexAtIsNull() {
            addCriterion("latest_index_at is null");
            return (Criteria) this;
        }

        public Criteria andLatestIndexAtIsNotNull() {
            addCriterion("latest_index_at is not null");
            return (Criteria) this;
        }

        public Criteria andLatestIndexAtEqualTo(Date value) {
            addCriterion("latest_index_at =", value, "latestIndexAt");
            return (Criteria) this;
        }

        public Criteria andLatestIndexAtNotEqualTo(Date value) {
            addCriterion("latest_index_at <>", value, "latestIndexAt");
            return (Criteria) this;
        }

        public Criteria andLatestIndexAtGreaterThan(Date value) {
            addCriterion("latest_index_at >", value, "latestIndexAt");
            return (Criteria) this;
        }

        public Criteria andLatestIndexAtGreaterThanOrEqualTo(Date value) {
            addCriterion("latest_index_at >=", value, "latestIndexAt");
            return (Criteria) this;
        }

        public Criteria andLatestIndexAtLessThan(Date value) {
            addCriterion("latest_index_at <", value, "latestIndexAt");
            return (Criteria) this;
        }

        public Criteria andLatestIndexAtLessThanOrEqualTo(Date value) {
            addCriterion("latest_index_at <=", value, "latestIndexAt");
            return (Criteria) this;
        }

        public Criteria andLatestIndexAtIn(List<Date> values) {
            addCriterion("latest_index_at in", values, "latestIndexAt");
            return (Criteria) this;
        }

        public Criteria andLatestIndexAtNotIn(List<Date> values) {
            addCriterion("latest_index_at not in", values, "latestIndexAt");
            return (Criteria) this;
        }

        public Criteria andLatestIndexAtBetween(Date value1, Date value2) {
            addCriterion("latest_index_at between", value1, value2, "latestIndexAt");
            return (Criteria) this;
        }

        public Criteria andLatestIndexAtNotBetween(Date value1, Date value2) {
            addCriterion("latest_index_at not between", value1, value2, "latestIndexAt");
            return (Criteria) this;
        }

        public Criteria andLastIndexAtIsNull() {
            addCriterion("last_index_at is null");
            return (Criteria) this;
        }

        public Criteria andLastIndexAtIsNotNull() {
            addCriterion("last_index_at is not null");
            return (Criteria) this;
        }

        public Criteria andLastIndexAtEqualTo(Date value) {
            addCriterion("last_index_at =", value, "lastIndexAt");
            return (Criteria) this;
        }

        public Criteria andLastIndexAtNotEqualTo(Date value) {
            addCriterion("last_index_at <>", value, "lastIndexAt");
            return (Criteria) this;
        }

        public Criteria andLastIndexAtGreaterThan(Date value) {
            addCriterion("last_index_at >", value, "lastIndexAt");
            return (Criteria) this;
        }

        public Criteria andLastIndexAtGreaterThanOrEqualTo(Date value) {
            addCriterion("last_index_at >=", value, "lastIndexAt");
            return (Criteria) this;
        }

        public Criteria andLastIndexAtLessThan(Date value) {
            addCriterion("last_index_at <", value, "lastIndexAt");
            return (Criteria) this;
        }

        public Criteria andLastIndexAtLessThanOrEqualTo(Date value) {
            addCriterion("last_index_at <=", value, "lastIndexAt");
            return (Criteria) this;
        }

        public Criteria andLastIndexAtIn(List<Date> values) {
            addCriterion("last_index_at in", values, "lastIndexAt");
            return (Criteria) this;
        }

        public Criteria andLastIndexAtNotIn(List<Date> values) {
            addCriterion("last_index_at not in", values, "lastIndexAt");
            return (Criteria) this;
        }

        public Criteria andLastIndexAtBetween(Date value1, Date value2) {
            addCriterion("last_index_at between", value1, value2, "lastIndexAt");
            return (Criteria) this;
        }

        public Criteria andLastIndexAtNotBetween(Date value1, Date value2) {
            addCriterion("last_index_at not between", value1, value2, "lastIndexAt");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table organization
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table organization
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}