package com.inmind.mybatis.entity;

import java.util.Date;

public class PrivateResumePO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_resume.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_resume.company_id
     *
     * @mbg.generated
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_resume.resume_id
     *
     * @mbg.generated
     */
    private Long resumeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_resume.people_id
     *
     * @mbg.generated
     */
    private Long peopleId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_resume.shared_to_account
     *
     * @mbg.generated
     */
    private Long sharedToAccount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_resume.created_by
     *
     * @mbg.generated
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_resume.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column private_resume.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_resume.id
     *
     * @return the value of private_resume.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_resume.id
     *
     * @param id the value for private_resume.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_resume.company_id
     *
     * @return the value of private_resume.company_id
     *
     * @mbg.generated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_resume.company_id
     *
     * @param companyId the value for private_resume.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_resume.resume_id
     *
     * @return the value of private_resume.resume_id
     *
     * @mbg.generated
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_resume.resume_id
     *
     * @param resumeId the value for private_resume.resume_id
     *
     * @mbg.generated
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_resume.people_id
     *
     * @return the value of private_resume.people_id
     *
     * @mbg.generated
     */
    public Long getPeopleId() {
        return peopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_resume.people_id
     *
     * @param peopleId the value for private_resume.people_id
     *
     * @mbg.generated
     */
    public void setPeopleId(Long peopleId) {
        this.peopleId = peopleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_resume.shared_to_account
     *
     * @return the value of private_resume.shared_to_account
     *
     * @mbg.generated
     */
    public Long getSharedToAccount() {
        return sharedToAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_resume.shared_to_account
     *
     * @param sharedToAccount the value for private_resume.shared_to_account
     *
     * @mbg.generated
     */
    public void setSharedToAccount(Long sharedToAccount) {
        this.sharedToAccount = sharedToAccount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_resume.created_by
     *
     * @return the value of private_resume.created_by
     *
     * @mbg.generated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_resume.created_by
     *
     * @param createdBy the value for private_resume.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_resume.created_at
     *
     * @return the value of private_resume.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_resume.created_at
     *
     * @param createdAt the value for private_resume.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column private_resume.updated_at
     *
     * @return the value of private_resume.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column private_resume.updated_at
     *
     * @param updatedAt the value for private_resume.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}