package com.inmind.mybatis.entity;

import java.util.Date;

public class ResumeLangPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_lang.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_lang.company_id
     *
     * @mbg.generated
     */
    private Long companyId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_lang.resume_id
     *
     * @mbg.generated
     */
    private Long resumeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_lang.lang_code
     *
     * @mbg.generated
     */
    private Integer langCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_lang.grade
     *
     * @mbg.generated
     */
    private Integer grade;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_lang.created_by
     *
     * @mbg.generated
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_lang.updated_by
     *
     * @mbg.generated
     */
    private Long updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_lang.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column resume_lang.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_lang.id
     *
     * @return the value of resume_lang.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_lang.id
     *
     * @param id the value for resume_lang.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_lang.company_id
     *
     * @return the value of resume_lang.company_id
     *
     * @mbg.generated
     */
    public Long getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_lang.company_id
     *
     * @param companyId the value for resume_lang.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(Long companyId) {
        this.companyId = companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_lang.resume_id
     *
     * @return the value of resume_lang.resume_id
     *
     * @mbg.generated
     */
    public Long getResumeId() {
        return resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_lang.resume_id
     *
     * @param resumeId the value for resume_lang.resume_id
     *
     * @mbg.generated
     */
    public void setResumeId(Long resumeId) {
        this.resumeId = resumeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_lang.lang_code
     *
     * @return the value of resume_lang.lang_code
     *
     * @mbg.generated
     */
    public Integer getLangCode() {
        return langCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_lang.lang_code
     *
     * @param langCode the value for resume_lang.lang_code
     *
     * @mbg.generated
     */
    public void setLangCode(Integer langCode) {
        this.langCode = langCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_lang.grade
     *
     * @return the value of resume_lang.grade
     *
     * @mbg.generated
     */
    public Integer getGrade() {
        return grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_lang.grade
     *
     * @param grade the value for resume_lang.grade
     *
     * @mbg.generated
     */
    public void setGrade(Integer grade) {
        this.grade = grade;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_lang.created_by
     *
     * @return the value of resume_lang.created_by
     *
     * @mbg.generated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_lang.created_by
     *
     * @param createdBy the value for resume_lang.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_lang.updated_by
     *
     * @return the value of resume_lang.updated_by
     *
     * @mbg.generated
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_lang.updated_by
     *
     * @param updatedBy the value for resume_lang.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_lang.created_at
     *
     * @return the value of resume_lang.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_lang.created_at
     *
     * @param createdAt the value for resume_lang.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column resume_lang.updated_at
     *
     * @return the value of resume_lang.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column resume_lang.updated_at
     *
     * @param updatedAt the value for resume_lang.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}