package com.inmind.mybatis.entity;

import java.util.Date;

public class TaskRelatedInterviewPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_related_interview.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_related_interview.task_id
     *
     * @mbg.generated
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_related_interview.task_interview_id
     *
     * @mbg.generated
     */
    private Long taskInterviewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_related_interview.created_by
     *
     * @mbg.generated
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_related_interview.updated_by
     *
     * @mbg.generated
     */
    private Long updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_related_interview.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_related_interview.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_related_interview.id
     *
     * @return the value of task_related_interview.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_related_interview.id
     *
     * @param id the value for task_related_interview.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_related_interview.task_id
     *
     * @return the value of task_related_interview.task_id
     *
     * @mbg.generated
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_related_interview.task_id
     *
     * @param taskId the value for task_related_interview.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_related_interview.task_interview_id
     *
     * @return the value of task_related_interview.task_interview_id
     *
     * @mbg.generated
     */
    public Long getTaskInterviewId() {
        return taskInterviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_related_interview.task_interview_id
     *
     * @param taskInterviewId the value for task_related_interview.task_interview_id
     *
     * @mbg.generated
     */
    public void setTaskInterviewId(Long taskInterviewId) {
        this.taskInterviewId = taskInterviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_related_interview.created_by
     *
     * @return the value of task_related_interview.created_by
     *
     * @mbg.generated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_related_interview.created_by
     *
     * @param createdBy the value for task_related_interview.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_related_interview.updated_by
     *
     * @return the value of task_related_interview.updated_by
     *
     * @mbg.generated
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_related_interview.updated_by
     *
     * @param updatedBy the value for task_related_interview.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_related_interview.created_at
     *
     * @return the value of task_related_interview.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_related_interview.created_at
     *
     * @param createdAt the value for task_related_interview.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_related_interview.updated_at
     *
     * @return the value of task_related_interview.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_related_interview.updated_at
     *
     * @param updatedAt the value for task_related_interview.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}