package com.inmind.mybatis.entity;

import java.util.Date;

public class TaskRemarkPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.owner_id
     *
     * @mbg.generated
     */
    private Long ownerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.relate_id
     *
     * @mbg.generated
     */
    private Long relateId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.task_id
     *
     * @mbg.generated
     */
    private Long taskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.question_form_id
     *
     * @mbg.generated
     */
    private Long questionFormId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.type
     *
     * @mbg.generated
     */
    private Integer type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.remark_ref_id
     *
     * @mbg.generated
     */
    private Long remarkRefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.submitted
     *
     * @mbg.generated
     */
    private Integer submitted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.deleted
     *
     * @mbg.generated
     */
    private Integer deleted;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.created_by
     *
     * @mbg.generated
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.updated_by
     *
     * @mbg.generated
     */
    private Long updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.task_ref_id
     *
     * @mbg.generated
     */
    private Long taskRefId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.task_type
     *
     * @mbg.generated
     */
    private Integer taskType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_remark.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.id
     *
     * @return the value of task_remark.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.id
     *
     * @param id the value for task_remark.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.owner_id
     *
     * @return the value of task_remark.owner_id
     *
     * @mbg.generated
     */
    public Long getOwnerId() {
        return ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.owner_id
     *
     * @param ownerId the value for task_remark.owner_id
     *
     * @mbg.generated
     */
    public void setOwnerId(Long ownerId) {
        this.ownerId = ownerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.relate_id
     *
     * @return the value of task_remark.relate_id
     *
     * @mbg.generated
     */
    public Long getRelateId() {
        return relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.relate_id
     *
     * @param relateId the value for task_remark.relate_id
     *
     * @mbg.generated
     */
    public void setRelateId(Long relateId) {
        this.relateId = relateId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.task_id
     *
     * @return the value of task_remark.task_id
     *
     * @mbg.generated
     */
    public Long getTaskId() {
        return taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.task_id
     *
     * @param taskId the value for task_remark.task_id
     *
     * @mbg.generated
     */
    public void setTaskId(Long taskId) {
        this.taskId = taskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.question_form_id
     *
     * @return the value of task_remark.question_form_id
     *
     * @mbg.generated
     */
    public Long getQuestionFormId() {
        return questionFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.question_form_id
     *
     * @param questionFormId the value for task_remark.question_form_id
     *
     * @mbg.generated
     */
    public void setQuestionFormId(Long questionFormId) {
        this.questionFormId = questionFormId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.type
     *
     * @return the value of task_remark.type
     *
     * @mbg.generated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.type
     *
     * @param type the value for task_remark.type
     *
     * @mbg.generated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.remark_ref_id
     *
     * @return the value of task_remark.remark_ref_id
     *
     * @mbg.generated
     */
    public Long getRemarkRefId() {
        return remarkRefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.remark_ref_id
     *
     * @param remarkRefId the value for task_remark.remark_ref_id
     *
     * @mbg.generated
     */
    public void setRemarkRefId(Long remarkRefId) {
        this.remarkRefId = remarkRefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.submitted
     *
     * @return the value of task_remark.submitted
     *
     * @mbg.generated
     */
    public Integer getSubmitted() {
        return submitted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.submitted
     *
     * @param submitted the value for task_remark.submitted
     *
     * @mbg.generated
     */
    public void setSubmitted(Integer submitted) {
        this.submitted = submitted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.deleted
     *
     * @return the value of task_remark.deleted
     *
     * @mbg.generated
     */
    public Integer getDeleted() {
        return deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.deleted
     *
     * @param deleted the value for task_remark.deleted
     *
     * @mbg.generated
     */
    public void setDeleted(Integer deleted) {
        this.deleted = deleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.created_by
     *
     * @return the value of task_remark.created_by
     *
     * @mbg.generated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.created_by
     *
     * @param createdBy the value for task_remark.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.updated_by
     *
     * @return the value of task_remark.updated_by
     *
     * @mbg.generated
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.updated_by
     *
     * @param updatedBy the value for task_remark.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.created_at
     *
     * @return the value of task_remark.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.created_at
     *
     * @param createdAt the value for task_remark.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.updated_at
     *
     * @return the value of task_remark.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.updated_at
     *
     * @param updatedAt the value for task_remark.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.task_ref_id
     *
     * @return the value of task_remark.task_ref_id
     *
     * @mbg.generated
     */
    public Long getTaskRefId() {
        return taskRefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.task_ref_id
     *
     * @param taskRefId the value for task_remark.task_ref_id
     *
     * @mbg.generated
     */
    public void setTaskRefId(Long taskRefId) {
        this.taskRefId = taskRefId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.task_type
     *
     * @return the value of task_remark.task_type
     *
     * @mbg.generated
     */
    public Integer getTaskType() {
        return taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.task_type
     *
     * @param taskType the value for task_remark.task_type
     *
     * @mbg.generated
     */
    public void setTaskType(Integer taskType) {
        this.taskType = taskType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_remark.remark
     *
     * @return the value of task_remark.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_remark.remark
     *
     * @param remark the value for task_remark.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }
}