package com.inmind.mybatis.entity;

import java.util.Date;

public class TaskFaceAssistTaskPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_task.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_task.face_interview_id
     *
     * @mbg.generated
     */
    private Long faceInterviewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_task.face_target_id
     *
     * @mbg.generated
     */
    private Long faceTargetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_task.assist_task_id
     *
     * @mbg.generated
     */
    private Long assistTaskId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_task.assist_target_id
     *
     * @mbg.generated
     */
    private Long assistTargetId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_task.created_by
     *
     * @mbg.generated
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_task.updated_by
     *
     * @mbg.generated
     */
    private Long updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_task.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_task.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_task.id
     *
     * @return the value of task_face_assist_task.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_task.id
     *
     * @param id the value for task_face_assist_task.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_task.face_interview_id
     *
     * @return the value of task_face_assist_task.face_interview_id
     *
     * @mbg.generated
     */
    public Long getFaceInterviewId() {
        return faceInterviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_task.face_interview_id
     *
     * @param faceInterviewId the value for task_face_assist_task.face_interview_id
     *
     * @mbg.generated
     */
    public void setFaceInterviewId(Long faceInterviewId) {
        this.faceInterviewId = faceInterviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_task.face_target_id
     *
     * @return the value of task_face_assist_task.face_target_id
     *
     * @mbg.generated
     */
    public Long getFaceTargetId() {
        return faceTargetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_task.face_target_id
     *
     * @param faceTargetId the value for task_face_assist_task.face_target_id
     *
     * @mbg.generated
     */
    public void setFaceTargetId(Long faceTargetId) {
        this.faceTargetId = faceTargetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_task.assist_task_id
     *
     * @return the value of task_face_assist_task.assist_task_id
     *
     * @mbg.generated
     */
    public Long getAssistTaskId() {
        return assistTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_task.assist_task_id
     *
     * @param assistTaskId the value for task_face_assist_task.assist_task_id
     *
     * @mbg.generated
     */
    public void setAssistTaskId(Long assistTaskId) {
        this.assistTaskId = assistTaskId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_task.assist_target_id
     *
     * @return the value of task_face_assist_task.assist_target_id
     *
     * @mbg.generated
     */
    public Long getAssistTargetId() {
        return assistTargetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_task.assist_target_id
     *
     * @param assistTargetId the value for task_face_assist_task.assist_target_id
     *
     * @mbg.generated
     */
    public void setAssistTargetId(Long assistTargetId) {
        this.assistTargetId = assistTargetId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_task.created_by
     *
     * @return the value of task_face_assist_task.created_by
     *
     * @mbg.generated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_task.created_by
     *
     * @param createdBy the value for task_face_assist_task.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_task.updated_by
     *
     * @return the value of task_face_assist_task.updated_by
     *
     * @mbg.generated
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_task.updated_by
     *
     * @param updatedBy the value for task_face_assist_task.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_task.created_at
     *
     * @return the value of task_face_assist_task.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_task.created_at
     *
     * @param createdAt the value for task_face_assist_task.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_task.updated_at
     *
     * @return the value of task_face_assist_task.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_task.updated_at
     *
     * @param updatedAt the value for task_face_assist_task.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}