package com.inmind.mybatis.entity;

import java.util.Date;

public class TaskFaceAssistAccountPO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_account.id
     *
     * @mbg.generated
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_account.face_interview_id
     *
     * @mbg.generated
     */
    private Long faceInterviewId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_account.assist_id
     *
     * @mbg.generated
     */
    private Long assistId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_account.assist_status
     *
     * @mbg.generated
     */
    private Integer assistStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_account.created_by
     *
     * @mbg.generated
     */
    private Long createdBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_account.updated_by
     *
     * @mbg.generated
     */
    private Long updatedBy;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_account.created_at
     *
     * @mbg.generated
     */
    private Date createdAt;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column task_face_assist_account.updated_at
     *
     * @mbg.generated
     */
    private Date updatedAt;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_account.id
     *
     * @return the value of task_face_assist_account.id
     *
     * @mbg.generated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_account.id
     *
     * @param id the value for task_face_assist_account.id
     *
     * @mbg.generated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_account.face_interview_id
     *
     * @return the value of task_face_assist_account.face_interview_id
     *
     * @mbg.generated
     */
    public Long getFaceInterviewId() {
        return faceInterviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_account.face_interview_id
     *
     * @param faceInterviewId the value for task_face_assist_account.face_interview_id
     *
     * @mbg.generated
     */
    public void setFaceInterviewId(Long faceInterviewId) {
        this.faceInterviewId = faceInterviewId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_account.assist_id
     *
     * @return the value of task_face_assist_account.assist_id
     *
     * @mbg.generated
     */
    public Long getAssistId() {
        return assistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_account.assist_id
     *
     * @param assistId the value for task_face_assist_account.assist_id
     *
     * @mbg.generated
     */
    public void setAssistId(Long assistId) {
        this.assistId = assistId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_account.assist_status
     *
     * @return the value of task_face_assist_account.assist_status
     *
     * @mbg.generated
     */
    public Integer getAssistStatus() {
        return assistStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_account.assist_status
     *
     * @param assistStatus the value for task_face_assist_account.assist_status
     *
     * @mbg.generated
     */
    public void setAssistStatus(Integer assistStatus) {
        this.assistStatus = assistStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_account.created_by
     *
     * @return the value of task_face_assist_account.created_by
     *
     * @mbg.generated
     */
    public Long getCreatedBy() {
        return createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_account.created_by
     *
     * @param createdBy the value for task_face_assist_account.created_by
     *
     * @mbg.generated
     */
    public void setCreatedBy(Long createdBy) {
        this.createdBy = createdBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_account.updated_by
     *
     * @return the value of task_face_assist_account.updated_by
     *
     * @mbg.generated
     */
    public Long getUpdatedBy() {
        return updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_account.updated_by
     *
     * @param updatedBy the value for task_face_assist_account.updated_by
     *
     * @mbg.generated
     */
    public void setUpdatedBy(Long updatedBy) {
        this.updatedBy = updatedBy;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_account.created_at
     *
     * @return the value of task_face_assist_account.created_at
     *
     * @mbg.generated
     */
    public Date getCreatedAt() {
        return createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_account.created_at
     *
     * @param createdAt the value for task_face_assist_account.created_at
     *
     * @mbg.generated
     */
    public void setCreatedAt(Date createdAt) {
        this.createdAt = createdAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column task_face_assist_account.updated_at
     *
     * @return the value of task_face_assist_account.updated_at
     *
     * @mbg.generated
     */
    public Date getUpdatedAt() {
        return updatedAt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column task_face_assist_account.updated_at
     *
     * @param updatedAt the value for task_face_assist_account.updated_at
     *
     * @mbg.generated
     */
    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }
}